<?php

namespace Database\Seeders;

use App\Models\Citie;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CitieSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $arrayData = [
            ['id'=>1,'name'=>'Abriaquí','departament_id'=>5],
            ['id'=>2,'name'=>'Acacías','departament_id'=>50],
            ['id'=>3,'name'=>'Acandí','departament_id'=>27],
            ['id'=>4,'name'=>'Acevedo','departament_id'=>41],
            ['id'=>5,'name'=>'Achí','departament_id'=>13],
            ['id'=>6,'name'=>'Agrado','departament_id'=>41],
            ['id'=>7,'name'=>'Agua de Dios','departament_id'=>25],
            ['id'=>8,'name'=>'Aguachica','departament_id'=>20],
            ['id'=>9,'name'=>'Aguada','departament_id'=>68],
            ['id'=>10,'name'=>'Aguadas','departament_id'=>17],
            ['id'=>11,'name'=>'Aguazul','departament_id'=>85],
            ['id'=>12,'name'=>'Agustín Codazzi','departament_id'=>20],
            ['id'=>13,'name'=>'Aipe','departament_id'=>41],
            ['id'=>14,'name'=>'Albania','departament_id'=>18],
            ['id'=>15,'name'=>'Albania','departament_id'=>44],
            ['id'=>16,'name'=>'Albania','departament_id'=>68],
            ['id'=>17,'name'=>'Albán','departament_id'=>25],
            ['id'=>18,'name'=>'Albán (San José)','departament_id'=>52],
            ['id'=>19,'name'=>'Alcalá','departament_id'=>76],
            ['id'=>20,'name'=>'Alejandria','departament_id'=>5],
            ['id'=>21,'name'=>'Algarrobo','departament_id'=>47],
            ['id'=>22,'name'=>'Algeciras','departament_id'=>41],
            ['id'=>23,'name'=>'Almaguer','departament_id'=>19],
            ['id'=>24,'name'=>'Almeida','departament_id'=>15],
            ['id'=>25,'name'=>'Alpujarra','departament_id'=>73],
            ['id'=>26,'name'=>'Altamira','departament_id'=>41],
            ['id'=>27,'name'=>'Alto Baudó (Pie de Pato)','departament_id'=>27],
            ['id'=>28,'name'=>'Altos del Rosario','departament_id'=>13],
            ['id'=>29,'name'=>'Alvarado','departament_id'=>73],
            ['id'=>30,'name'=>'Amagá','departament_id'=>5],
            ['id'=>31,'name'=>'Amalfi','departament_id'=>5],
            ['id'=>32,'name'=>'Ambalema','departament_id'=>73],
            ['id'=>33,'name'=>'Anapoima','departament_id'=>25],
            ['id'=>34,'name'=>'Ancuya','departament_id'=>52],
            ['id'=>35,'name'=>'Andalucía','departament_id'=>76],
            ['id'=>36,'name'=>'Andes','departament_id'=>5],
            ['id'=>37,'name'=>'Angelópolis','departament_id'=>5],
            ['id'=>38,'name'=>'Angostura','departament_id'=>5],
            ['id'=>39,'name'=>'Anolaima','departament_id'=>25],
            ['id'=>40,'name'=>'Anorí','departament_id'=>5],
            ['id'=>41,'name'=>'Anserma','departament_id'=>17],
            ['id'=>42,'name'=>'Ansermanuevo','departament_id'=>76],
            ['id'=>43,'name'=>'Anzoátegui','departament_id'=>73],
            ['id'=>44,'name'=>'Anzá','departament_id'=>5],
            ['id'=>45,'name'=>'Apartadó','departament_id'=>5],
            ['id'=>46,'name'=>'Apulo','departament_id'=>25],
            ['id'=>47,'name'=>'Apía','departament_id'=>66],
            ['id'=>48,'name'=>'Aquitania','departament_id'=>15],
            ['id'=>49,'name'=>'Aracataca','departament_id'=>47],
            ['id'=>50,'name'=>'Aranzazu','departament_id'=>17],
            ['id'=>51,'name'=>'Aratoca','departament_id'=>68],
            ['id'=>52,'name'=>'Arauca','departament_id'=>81],
            ['id'=>53,'name'=>'Arauquita','departament_id'=>81],
            ['id'=>54,'name'=>'Arbeláez','departament_id'=>25],
            ['id'=>55,'name'=>'Arboleda (Berruecos)','departament_id'=>52],
            ['id'=>56,'name'=>'Arboledas','departament_id'=>54],
            ['id'=>57,'name'=>'Arboletes','departament_id'=>5],
            ['id'=>58,'name'=>'Arcabuco','departament_id'=>15],
            ['id'=>59,'name'=>'Arenal','departament_id'=>13],
            ['id'=>60,'name'=>'Argelia','departament_id'=>5],
            ['id'=>61,'name'=>'Argelia','departament_id'=>19],
            ['id'=>62,'name'=>'Argelia','departament_id'=>76],
            ['id'=>63,'name'=>'Ariguaní (El Difícil)','departament_id'=>47],
            ['id'=>64,'name'=>'Arjona','departament_id'=>13],
            ['id'=>65,'name'=>'Armenia','departament_id'=>5],
            ['id'=>66,'name'=>'Armenia','departament_id'=>63],
            ['id'=>67,'name'=>'Armero (Guayabal)','departament_id'=>73],
            ['id'=>68,'name'=>'Arroyohondo','departament_id'=>13],
            ['id'=>69,'name'=>'Astrea','departament_id'=>20],
            ['id'=>70,'name'=>'Ataco','departament_id'=>73],
            ['id'=>71,'name'=>'Atrato (Yuto)','departament_id'=>27],
            ['id'=>72,'name'=>'Ayapel','departament_id'=>23],
            ['id'=>73,'name'=>'Bagadó','departament_id'=>27],
            ['id'=>74,'name'=>'Bahía Solano (Mútis)','departament_id'=>27],
            ['id'=>75,'name'=>'Bajo Baudó (Pizarro)','departament_id'=>27],
            ['id'=>76,'name'=>'Balboa','departament_id'=>19],
            ['id'=>77,'name'=>'Balboa','departament_id'=>66],
            ['id'=>78,'name'=>'Baranoa','departament_id'=>8],
            ['id'=>79,'name'=>'Baraya','departament_id'=>41],
            ['id'=>80,'name'=>'Barbacoas','departament_id'=>52],
            ['id'=>81,'name'=>'Barbosa','departament_id'=>5],
            ['id'=>82,'name'=>'Barbosa','departament_id'=>68],
            ['id'=>83,'name'=>'Barichara','departament_id'=>68],
            ['id'=>84,'name'=>'Barranca de Upía','departament_id'=>50],
            ['id'=>85,'name'=>'Barrancabermeja','departament_id'=>68],
            ['id'=>86,'name'=>'Barrancas','departament_id'=>44],
            ['id'=>87,'name'=>'Barranco de Loba','departament_id'=>13],
            ['id'=>88,'name'=>'Barranquilla','departament_id'=>8],
            ['id'=>89,'name'=>'Becerríl','departament_id'=>20],
            ['id'=>90,'name'=>'Belalcázar','departament_id'=>17],
            ['id'=>91,'name'=>'Bello','departament_id'=>5],
            ['id'=>92,'name'=>'Belmira','departament_id'=>5],
            ['id'=>93,'name'=>'Beltrán','departament_id'=>25],
            ['id'=>94,'name'=>'Belén','departament_id'=>15],
            ['id'=>95,'name'=>'Belén','departament_id'=>52],
            ['id'=>96,'name'=>'Belén de Bajirá','departament_id'=>27],
            ['id'=>97,'name'=>'Belén de Umbría','departament_id'=>66],
            ['id'=>98,'name'=>'Belén de los Andaquíes','departament_id'=>18],
            ['id'=>99,'name'=>'Berbeo','departament_id'=>15],
            ['id'=>100,'name'=>'Betania','departament_id'=>5],
            ['id'=>101,'name'=>'Beteitiva','departament_id'=>15],
            ['id'=>102,'name'=>'Betulia','departament_id'=>5],
            ['id'=>103,'name'=>'Betulia','departament_id'=>68],
            ['id'=>104,'name'=>'Bituima','departament_id'=>25],
            ['id'=>105,'name'=>'Boavita','departament_id'=>15],
            ['id'=>106,'name'=>'Bochalema','departament_id'=>54],
            ['id'=>107,'name'=>'Bogotá D.C.','departament_id'=>11],
            ['id'=>108,'name'=>'Bojacá','departament_id'=>25],
            ['id'=>109,'name'=>'Bojayá (Bellavista)','departament_id'=>27],
            ['id'=>110,'name'=>'Bolívar','departament_id'=>5],
            ['id'=>111,'name'=>'Bolívar','departament_id'=>19],
            ['id'=>112,'name'=>'Bolívar','departament_id'=>68],
            ['id'=>113,'name'=>'Bolívar','departament_id'=>76],
            ['id'=>114,'name'=>'Bosconia','departament_id'=>20],
            ['id'=>115,'name'=>'Boyacá','departament_id'=>15],
            ['id'=>116,'name'=>'Briceño','departament_id'=>5],
            ['id'=>117,'name'=>'Briceño','departament_id'=>15],
            ['id'=>118,'name'=>'Bucaramanga','departament_id'=>68],
            ['id'=>119,'name'=>'Bucarasica','departament_id'=>54],
            ['id'=>120,'name'=>'Buenaventura','departament_id'=>76],
            ['id'=>121,'name'=>'Buenavista','departament_id'=>15],
            ['id'=>122,'name'=>'Buenavista','departament_id'=>23],
            ['id'=>123,'name'=>'Buenavista','departament_id'=>63],
            ['id'=>124,'name'=>'Buenavista','departament_id'=>70],
            ['id'=>125,'name'=>'Buenos Aires','departament_id'=>19],
            ['id'=>126,'name'=>'Buesaco','departament_id'=>52],
            ['id'=>127,'name'=>'Buga','departament_id'=>76],
            ['id'=>128,'name'=>'Bugalagrande','departament_id'=>76],
            ['id'=>129,'name'=>'Burítica','departament_id'=>5],
            ['id'=>130,'name'=>'Busbanza','departament_id'=>15],
            ['id'=>131,'name'=>'Cabrera','departament_id'=>25],
            ['id'=>132,'name'=>'Cabrera','departament_id'=>68],
            ['id'=>133,'name'=>'Cabuyaro','departament_id'=>50],
            ['id'=>134,'name'=>'Cachipay','departament_id'=>25],
            ['id'=>135,'name'=>'Caicedo','departament_id'=>5],
            ['id'=>136,'name'=>'Caicedonia','departament_id'=>76],
            ['id'=>137,'name'=>'Caimito','departament_id'=>70],
            ['id'=>138,'name'=>'Cajamarca','departament_id'=>73],
            ['id'=>139,'name'=>'Cajibío','departament_id'=>19],
            ['id'=>140,'name'=>'Cajicá','departament_id'=>25],
            ['id'=>141,'name'=>'Calamar','departament_id'=>13],
            ['id'=>142,'name'=>'Calamar','departament_id'=>95],
            ['id'=>143,'name'=>'Calarcá','departament_id'=>63],
            ['id'=>144,'name'=>'Caldas','departament_id'=>5],
            ['id'=>145,'name'=>'Caldas','departament_id'=>15],
            ['id'=>146,'name'=>'Caldono','departament_id'=>19],
            ['id'=>147,'name'=>'California','departament_id'=>68],
            ['id'=>148,'name'=>'Calima (Darién)','departament_id'=>76],
            ['id'=>149,'name'=>'Caloto','departament_id'=>19],
            ['id'=>150,'name'=>'Calí','departament_id'=>76],
            ['id'=>151,'name'=>'Campamento','departament_id'=>5],
            ['id'=>152,'name'=>'Campo de la Cruz','departament_id'=>8],
            ['id'=>153,'name'=>'Campoalegre','departament_id'=>41],
            ['id'=>154,'name'=>'Campohermoso','departament_id'=>15],
            ['id'=>155,'name'=>'Canalete','departament_id'=>23],
            ['id'=>156,'name'=>'Candelaria','departament_id'=>8],
            ['id'=>157,'name'=>'Candelaria','departament_id'=>76],
            ['id'=>158,'name'=>'Cantagallo','departament_id'=>13],
            ['id'=>159,'name'=>'Cantón de San Pablo','departament_id'=>27],
            ['id'=>160,'name'=>'Caparrapí','departament_id'=>25],
            ['id'=>161,'name'=>'Capitanejo','departament_id'=>68],
            ['id'=>162,'name'=>'Caracolí','departament_id'=>5],
            ['id'=>163,'name'=>'Caramanta','departament_id'=>5],
            ['id'=>164,'name'=>'Carcasí','departament_id'=>68],
            ['id'=>165,'name'=>'Carepa','departament_id'=>5],
            ['id'=>166,'name'=>'Carmen de Apicalá','departament_id'=>73],
            ['id'=>167,'name'=>'Carmen de Carupa','departament_id'=>25],
            ['id'=>168,'name'=>'Carmen de Viboral','departament_id'=>5],
            ['id'=>169,'name'=>'Carmen del Darién (CURBARADÓ)','departament_id'=>27],
            ['id'=>170,'name'=>'Carolina','departament_id'=>5],
            ['id'=>171,'name'=>'Cartagena','departament_id'=>13],
            ['id'=>172,'name'=>'Cartagena del Chairá','departament_id'=>18],
            ['id'=>173,'name'=>'Cartago','departament_id'=>76],
            ['id'=>174,'name'=>'Carurú','departament_id'=>97],
            ['id'=>175,'name'=>'Casabianca','departament_id'=>73],
            ['id'=>176,'name'=>'Castilla la Nueva','departament_id'=>50],
            ['id'=>177,'name'=>'Caucasia','departament_id'=>5],
            ['id'=>178,'name'=>'Cañasgordas','departament_id'=>5],
            ['id'=>179,'name'=>'Cepita','departament_id'=>68],
            ['id'=>180,'name'=>'Cereté','departament_id'=>23],
            ['id'=>181,'name'=>'Cerinza','departament_id'=>15],
            ['id'=>182,'name'=>'Cerrito','departament_id'=>68],
            ['id'=>183,'name'=>'Cerro San Antonio','departament_id'=>47],
            ['id'=>184,'name'=>'Chachaguí','departament_id'=>52],
            ['id'=>185,'name'=>'Chaguaní','departament_id'=>25],
            ['id'=>186,'name'=>'Chalán','departament_id'=>70],
            ['id'=>187,'name'=>'Chaparral','departament_id'=>73],
            ['id'=>188,'name'=>'Charalá','departament_id'=>68],
            ['id'=>189,'name'=>'Charta','departament_id'=>68],
            ['id'=>190,'name'=>'Chigorodó','departament_id'=>5],
            ['id'=>191,'name'=>'Chima','departament_id'=>68],
            ['id'=>192,'name'=>'Chimichagua','departament_id'=>20],
            ['id'=>193,'name'=>'Chimá','departament_id'=>23],
            ['id'=>194,'name'=>'Chinavita','departament_id'=>15],
            ['id'=>195,'name'=>'Chinchiná','departament_id'=>17],
            ['id'=>196,'name'=>'Chinácota','departament_id'=>54],
            ['id'=>197,'name'=>'Chinú','departament_id'=>23],
            ['id'=>198,'name'=>'Chipaque','departament_id'=>25],
            ['id'=>199,'name'=>'Chipatá','departament_id'=>68],
            ['id'=>200,'name'=>'Chiquinquirá','departament_id'=>15],
            ['id'=>201,'name'=>'Chiriguaná','departament_id'=>20],
            ['id'=>202,'name'=>'Chiscas','departament_id'=>15],
            ['id'=>203,'name'=>'Chita','departament_id'=>15],
            ['id'=>204,'name'=>'Chitagá','departament_id'=>54],
            ['id'=>205,'name'=>'Chitaraque','departament_id'=>15],
            ['id'=>206,'name'=>'Chivatá','departament_id'=>15],
            ['id'=>207,'name'=>'Chivolo','departament_id'=>47],
            ['id'=>208,'name'=>'Choachí','departament_id'=>25],
            ['id'=>209,'name'=>'Chocontá','departament_id'=>25],
            ['id'=>210,'name'=>'Chámeza','departament_id'=>85],
            ['id'=>211,'name'=>'Chía','departament_id'=>25],
            ['id'=>212,'name'=>'Chíquiza','departament_id'=>15],
            ['id'=>213,'name'=>'Chívor','departament_id'=>15],
            ['id'=>214,'name'=>'Cicuco','departament_id'=>13],
            ['id'=>215,'name'=>'Cimitarra','departament_id'=>68],
            ['id'=>216,'name'=>'Circasia','departament_id'=>63],
            ['id'=>217,'name'=>'Cisneros','departament_id'=>5],
            ['id'=>218,'name'=>'Ciénaga','departament_id'=>15],
            ['id'=>219,'name'=>'Ciénaga','departament_id'=>47],
            ['id'=>220,'name'=>'Ciénaga de Oro','departament_id'=>23],
            ['id'=>221,'name'=>'Clemencia','departament_id'=>13],
            ['id'=>222,'name'=>'Cocorná','departament_id'=>5],
            ['id'=>223,'name'=>'Coello','departament_id'=>73],
            ['id'=>224,'name'=>'Cogua','departament_id'=>25],
            ['id'=>225,'name'=>'Colombia','departament_id'=>41],
            ['id'=>226,'name'=>'Colosó (Ricaurte)','departament_id'=>70],
            ['id'=>227,'name'=>'Colón','departament_id'=>86],
            ['id'=>228,'name'=>'Colón (Génova)','departament_id'=>52],
            ['id'=>229,'name'=>'Concepción','departament_id'=>5],
            ['id'=>230,'name'=>'Concepción','departament_id'=>68],
            ['id'=>231,'name'=>'Concordia','departament_id'=>5],
            ['id'=>232,'name'=>'Concordia','departament_id'=>47],
            ['id'=>233,'name'=>'Condoto','departament_id'=>27],
            ['id'=>234,'name'=>'Confines','departament_id'=>68],
            ['id'=>235,'name'=>'Consaca','departament_id'=>52],
            ['id'=>236,'name'=>'Contadero','departament_id'=>52],
            ['id'=>237,'name'=>'Contratación','departament_id'=>68],
            ['id'=>238,'name'=>'Convención','departament_id'=>54],
            ['id'=>239,'name'=>'Copacabana','departament_id'=>5],
            ['id'=>240,'name'=>'Coper','departament_id'=>15],
            ['id'=>241,'name'=>'Cordobá','departament_id'=>63],
            ['id'=>242,'name'=>'Corinto','departament_id'=>19],
            ['id'=>243,'name'=>'Coromoro','departament_id'=>68],
            ['id'=>244,'name'=>'Corozal','departament_id'=>70],
            ['id'=>245,'name'=>'Corrales','departament_id'=>15],
            ['id'=>246,'name'=>'Cota','departament_id'=>25],
            ['id'=>247,'name'=>'Cotorra','departament_id'=>23],
            ['id'=>248,'name'=>'Covarachía','departament_id'=>15],
            ['id'=>249,'name'=>'Coveñas','departament_id'=>70],
            ['id'=>250,'name'=>'Coyaima','departament_id'=>73],
            ['id'=>251,'name'=>'Cravo Norte','departament_id'=>81],
            ['id'=>252,'name'=>'Cuaspud (Carlosama)','departament_id'=>52],
            ['id'=>253,'name'=>'Cubarral','departament_id'=>50],
            ['id'=>254,'name'=>'Cubará','departament_id'=>15],
            ['id'=>255,'name'=>'Cucaita','departament_id'=>15],
            ['id'=>256,'name'=>'Cucunubá','departament_id'=>25],
            ['id'=>257,'name'=>'Cucutilla','departament_id'=>54],
            ['id'=>258,'name'=>'Cuitiva','departament_id'=>15],
            ['id'=>259,'name'=>'Cumaral','departament_id'=>50],
            ['id'=>260,'name'=>'Cumaribo','departament_id'=>99],
            ['id'=>261,'name'=>'Cumbal','departament_id'=>52],
            ['id'=>262,'name'=>'Cumbitara','departament_id'=>52],
            ['id'=>263,'name'=>'Cunday','departament_id'=>73],
            ['id'=>264,'name'=>'Curillo','departament_id'=>18],
            ['id'=>265,'name'=>'Curití','departament_id'=>68],
            ['id'=>266,'name'=>'Curumaní','departament_id'=>20],
            ['id'=>267,'name'=>'Cáceres','departament_id'=>5],
            ['id'=>268,'name'=>'Cáchira','departament_id'=>54],
            ['id'=>269,'name'=>'Cácota','departament_id'=>54],
            ['id'=>270,'name'=>'Cáqueza','departament_id'=>25],
            ['id'=>271,'name'=>'Cértegui','departament_id'=>27],
            ['id'=>272,'name'=>'Cómbita','departament_id'=>15],
            ['id'=>273,'name'=>'Córdoba','departament_id'=>13],
            ['id'=>274,'name'=>'Córdoba','departament_id'=>52],
            ['id'=>275,'name'=>'Cúcuta','departament_id'=>54],
            ['id'=>276,'name'=>'Dabeiba','departament_id'=>5],
            ['id'=>277,'name'=>'Dagua','departament_id'=>76],
            ['id'=>278,'name'=>'Dibulla','departament_id'=>44],
            ['id'=>279,'name'=>'Distracción','departament_id'=>44],
            ['id'=>280,'name'=>'Dolores','departament_id'=>73],
            ['id'=>281,'name'=>'Don Matías','departament_id'=>5],
            ['id'=>282,'name'=>'Dos Quebradas','departament_id'=>66],
            ['id'=>283,'name'=>'Duitama','departament_id'=>15],
            ['id'=>284,'name'=>'Durania','departament_id'=>54],
            ['id'=>285,'name'=>'Ebéjico','departament_id'=>5],
            ['id'=>286,'name'=>'El Bagre','departament_id'=>5],
            ['id'=>287,'name'=>'El Banco','departament_id'=>47],
            ['id'=>288,'name'=>'El Cairo','departament_id'=>76],
            ['id'=>289,'name'=>'El Calvario','departament_id'=>50],
            ['id'=>290,'name'=>'El Carmen','departament_id'=>54],
            ['id'=>291,'name'=>'El Carmen','departament_id'=>68],
            ['id'=>292,'name'=>'El Carmen de Atrato','departament_id'=>27],
            ['id'=>293,'name'=>'El Carmen de Bolívar','departament_id'=>13],
            ['id'=>294,'name'=>'El Castillo','departament_id'=>50],
            ['id'=>295,'name'=>'El Cerrito','departament_id'=>76],
            ['id'=>296,'name'=>'El Charco','departament_id'=>52],
            ['id'=>297,'name'=>'El Cocuy','departament_id'=>15],
            ['id'=>298,'name'=>'El Colegio','departament_id'=>25],
            ['id'=>299,'name'=>'El Copey','departament_id'=>20],
            ['id'=>300,'name'=>'El Doncello','departament_id'=>18],
            ['id'=>301,'name'=>'El Dorado','departament_id'=>50],
            ['id'=>302,'name'=>'El Dovio','departament_id'=>76],
            ['id'=>303,'name'=>'El Espino','departament_id'=>15],
            ['id'=>304,'name'=>'El Guacamayo','departament_id'=>68],
            ['id'=>305,'name'=>'El Guamo','departament_id'=>13],
            ['id'=>306,'name'=>'El Molino','departament_id'=>44],
            ['id'=>307,'name'=>'El Paso','departament_id'=>20],
            ['id'=>308,'name'=>'El Paujil','departament_id'=>18],
            ['id'=>309,'name'=>'El Peñol','departament_id'=>52],
            ['id'=>310,'name'=>'El Peñon','departament_id'=>13],
            ['id'=>311,'name'=>'El Peñon','departament_id'=>68],
            ['id'=>312,'name'=>'El Peñón','departament_id'=>25],
            ['id'=>313,'name'=>'El Piñon','departament_id'=>47],
            ['id'=>314,'name'=>'El Playón','departament_id'=>68],
            ['id'=>315,'name'=>'El Retorno','departament_id'=>95],
            ['id'=>316,'name'=>'El Retén','departament_id'=>47],
            ['id'=>317,'name'=>'El Roble','departament_id'=>70],
            ['id'=>318,'name'=>'El Rosal','departament_id'=>25],
            ['id'=>319,'name'=>'El Rosario','departament_id'=>52],
            ['id'=>320,'name'=>'El Tablón de Gómez','departament_id'=>52],
            ['id'=>321,'name'=>'El Tambo','departament_id'=>19],
            ['id'=>322,'name'=>'El Tambo','departament_id'=>52],
            ['id'=>323,'name'=>'El Tarra','departament_id'=>54],
            ['id'=>324,'name'=>'El Zulia','departament_id'=>54],
            ['id'=>325,'name'=>'El Águila','departament_id'=>76],
            ['id'=>326,'name'=>'Elías','departament_id'=>41],
            ['id'=>327,'name'=>'Encino','departament_id'=>68],
            ['id'=>328,'name'=>'Enciso','departament_id'=>68],
            ['id'=>329,'name'=>'Entrerríos','departament_id'=>5],
            ['id'=>330,'name'=>'Envigado','departament_id'=>5],
            ['id'=>331,'name'=>'Espinal','departament_id'=>73],
            ['id'=>332,'name'=>'Facatativá','departament_id'=>25],
            ['id'=>333,'name'=>'Falan','departament_id'=>73],
            ['id'=>334,'name'=>'Filadelfia','departament_id'=>17],
            ['id'=>335,'name'=>'Filandia','departament_id'=>63],
            ['id'=>336,'name'=>'Firavitoba','departament_id'=>15],
            ['id'=>337,'name'=>'Flandes','departament_id'=>73],
            ['id'=>338,'name'=>'Florencia','departament_id'=>18],
            ['id'=>339,'name'=>'Florencia','departament_id'=>19],
            ['id'=>340,'name'=>'Floresta','departament_id'=>15],
            ['id'=>341,'name'=>'Florida','departament_id'=>76],
            ['id'=>342,'name'=>'Floridablanca','departament_id'=>68],
            ['id'=>343,'name'=>'Florián','departament_id'=>68],
            ['id'=>344,'name'=>'Fonseca','departament_id'=>44],
            ['id'=>345,'name'=>'Fortúl','departament_id'=>81],
            ['id'=>346,'name'=>'Fosca','departament_id'=>25],
            ['id'=>347,'name'=>'Francisco Pizarro','departament_id'=>52],
            ['id'=>348,'name'=>'Fredonia','departament_id'=>5],
            ['id'=>349,'name'=>'Fresno','departament_id'=>73],
            ['id'=>350,'name'=>'Frontino','departament_id'=>5],
            ['id'=>351,'name'=>'Fuente de Oro','departament_id'=>50],
            ['id'=>352,'name'=>'Fundación','departament_id'=>47],
            ['id'=>353,'name'=>'Funes','departament_id'=>52],
            ['id'=>354,'name'=>'Funza','departament_id'=>25],
            ['id'=>355,'name'=>'Fusagasugá','departament_id'=>25],
            ['id'=>356,'name'=>'Fómeque','departament_id'=>25],
            ['id'=>357,'name'=>'Fúquene','departament_id'=>25],
            ['id'=>358,'name'=>'Gachalá','departament_id'=>25],
            ['id'=>359,'name'=>'Gachancipá','departament_id'=>25],
            ['id'=>360,'name'=>'Gachantivá','departament_id'=>15],
            ['id'=>361,'name'=>'Gachetá','departament_id'=>25],
            ['id'=>362,'name'=>'Galapa','departament_id'=>8],
            ['id'=>363,'name'=>'Galeras (Nueva Granada)','departament_id'=>70],
            ['id'=>364,'name'=>'Galán','departament_id'=>68],
            ['id'=>365,'name'=>'Gama','departament_id'=>25],
            ['id'=>366,'name'=>'Gamarra','departament_id'=>20],
            ['id'=>367,'name'=>'Garagoa','departament_id'=>15],
            ['id'=>368,'name'=>'Garzón','departament_id'=>41],
            ['id'=>369,'name'=>'Gigante','departament_id'=>41],
            ['id'=>370,'name'=>'Ginebra','departament_id'=>76],
            ['id'=>371,'name'=>'Giraldo','departament_id'=>5],
            ['id'=>372,'name'=>'Girardot','departament_id'=>25],
            ['id'=>373,'name'=>'Girardota','departament_id'=>5],
            ['id'=>374,'name'=>'Girón','departament_id'=>68],
            ['id'=>375,'name'=>'Gonzalez','departament_id'=>20],
            ['id'=>376,'name'=>'Gramalote','departament_id'=>54],
            ['id'=>377,'name'=>'Granada','departament_id'=>5],
            ['id'=>378,'name'=>'Granada','departament_id'=>25],
            ['id'=>379,'name'=>'Granada','departament_id'=>50],
            ['id'=>380,'name'=>'Guaca','departament_id'=>68],
            ['id'=>381,'name'=>'Guacamayas','departament_id'=>15],
            ['id'=>382,'name'=>'Guacarí','departament_id'=>76],
            ['id'=>383,'name'=>'Guachavés','departament_id'=>52],
            ['id'=>384,'name'=>'Guachené','departament_id'=>19],
            ['id'=>385,'name'=>'Guachetá','departament_id'=>25],
            ['id'=>386,'name'=>'Guachucal','departament_id'=>52],
            ['id'=>387,'name'=>'Guadalupe','departament_id'=>5],
            ['id'=>388,'name'=>'Guadalupe','departament_id'=>41],
            ['id'=>389,'name'=>'Guadalupe','departament_id'=>68],
            ['id'=>390,'name'=>'Guaduas','departament_id'=>25],
            ['id'=>391,'name'=>'Guaitarilla','departament_id'=>52],
            ['id'=>392,'name'=>'Gualmatán','departament_id'=>52],
            ['id'=>393,'name'=>'Guamal','departament_id'=>47],
            ['id'=>394,'name'=>'Guamal','departament_id'=>50],
            ['id'=>395,'name'=>'Guamo','departament_id'=>73],
            ['id'=>396,'name'=>'Guapota','departament_id'=>68],
            ['id'=>397,'name'=>'Guapí','departament_id'=>19],
            ['id'=>398,'name'=>'Guaranda','departament_id'=>70],
            ['id'=>399,'name'=>'Guarne','departament_id'=>5],
            ['id'=>400,'name'=>'Guasca','departament_id'=>25],
            ['id'=>401,'name'=>'Guatapé','departament_id'=>5],
            ['id'=>402,'name'=>'Guataquí','departament_id'=>25],
            ['id'=>403,'name'=>'Guatavita','departament_id'=>25],
            ['id'=>404,'name'=>'Guateque','departament_id'=>15],
            ['id'=>405,'name'=>'Guavatá','departament_id'=>68],
            ['id'=>406,'name'=>'Guayabal de Siquima','departament_id'=>25],
            ['id'=>407,'name'=>'Guayabetal','departament_id'=>25],
            ['id'=>408,'name'=>'Guayatá','departament_id'=>15],
            ['id'=>409,'name'=>'Guepsa','departament_id'=>68],
            ['id'=>410,'name'=>'Guicán','departament_id'=>15],
            ['id'=>411,'name'=>'Gutiérrez','departament_id'=>25],
            ['id'=>412,'name'=>'Guática','departament_id'=>66],
            ['id'=>413,'name'=>'Gámbita','departament_id'=>68],
            ['id'=>414,'name'=>'Gámeza','departament_id'=>15],
            ['id'=>415,'name'=>'Génova','departament_id'=>63],
            ['id'=>416,'name'=>'Gómez Plata','departament_id'=>5],
            ['id'=>417,'name'=>'Hacarí','departament_id'=>54],
            ['id'=>418,'name'=>'Hatillo de Loba','departament_id'=>13],
            ['id'=>419,'name'=>'Hato','departament_id'=>68],
            ['id'=>420,'name'=>'Hato Corozal','departament_id'=>85],
            ['id'=>421,'name'=>'Hatonuevo','departament_id'=>44],
            ['id'=>422,'name'=>'Heliconia','departament_id'=>5],
            ['id'=>423,'name'=>'Herrán','departament_id'=>54],
            ['id'=>424,'name'=>'Herveo','departament_id'=>73],
            ['id'=>425,'name'=>'Hispania','departament_id'=>5],
            ['id'=>426,'name'=>'Hobo','departament_id'=>41],
            ['id'=>427,'name'=>'Honda','departament_id'=>73],
            ['id'=>428,'name'=>'Ibagué','departament_id'=>73],
            ['id'=>429,'name'=>'Icononzo','departament_id'=>73],
            ['id'=>430,'name'=>'Iles','departament_id'=>52],
            ['id'=>431,'name'=>'Imúes','departament_id'=>52],
            ['id'=>432,'name'=>'Inzá','departament_id'=>19],
            ['id'=>433,'name'=>'Inírida','departament_id'=>94],
            ['id'=>434,'name'=>'Ipiales','departament_id'=>52],
            ['id'=>435,'name'=>'Isnos','departament_id'=>41],
            ['id'=>436,'name'=>'Istmina','departament_id'=>27],
            ['id'=>437,'name'=>'Itagüí','departament_id'=>5],
            ['id'=>438,'name'=>'Ituango','departament_id'=>5],
            ['id'=>439,'name'=>'Izá','departament_id'=>15],
            ['id'=>440,'name'=>'Jambaló','departament_id'=>19],
            ['id'=>441,'name'=>'Jamundí','departament_id'=>76],
            ['id'=>442,'name'=>'Jardín','departament_id'=>5],
            ['id'=>443,'name'=>'Jenesano','departament_id'=>15],
            ['id'=>444,'name'=>'Jericó','departament_id'=>5],
            ['id'=>445,'name'=>'Jericó','departament_id'=>15],
            ['id'=>446,'name'=>'Jerusalén','departament_id'=>25],
            ['id'=>447,'name'=>'Jesús María','departament_id'=>68],
            ['id'=>448,'name'=>'Jordán','departament_id'=>68],
            ['id'=>449,'name'=>'Juan de Acosta','departament_id'=>8],
            ['id'=>450,'name'=>'Junín','departament_id'=>25],
            ['id'=>451,'name'=>'Juradó','departament_id'=>27],
            ['id'=>452,'name'=>'La Apartada y La Frontera','departament_id'=>23],
            ['id'=>453,'name'=>'La Argentina','departament_id'=>41],
            ['id'=>454,'name'=>'La Belleza','departament_id'=>68],
            ['id'=>455,'name'=>'La Calera','departament_id'=>25],
            ['id'=>456,'name'=>'La Capilla','departament_id'=>15],
            ['id'=>457,'name'=>'La Ceja','departament_id'=>5],
            ['id'=>458,'name'=>'La Celia','departament_id'=>66],
            ['id'=>459,'name'=>'La Cruz','departament_id'=>52],
            ['id'=>460,'name'=>'La Cumbre','departament_id'=>76],
            ['id'=>461,'name'=>'La Dorada','departament_id'=>17],
            ['id'=>462,'name'=>'La Esperanza','departament_id'=>54],
            ['id'=>463,'name'=>'La Estrella','departament_id'=>5],
            ['id'=>464,'name'=>'La Florida','departament_id'=>52],
            ['id'=>465,'name'=>'La Gloria','departament_id'=>20],
            ['id'=>466,'name'=>'La Jagua de Ibirico','departament_id'=>20],
            ['id'=>467,'name'=>'La Jagua del Pilar','departament_id'=>44],
            ['id'=>468,'name'=>'La Llanada','departament_id'=>52],
            ['id'=>469,'name'=>'La Macarena','departament_id'=>50],
            ['id'=>470,'name'=>'La Merced','departament_id'=>17],
            ['id'=>471,'name'=>'La Mesa','departament_id'=>25],
            ['id'=>472,'name'=>'La Montañita','departament_id'=>18],
            ['id'=>473,'name'=>'La Palma','departament_id'=>25],
            ['id'=>474,'name'=>'La Paz','departament_id'=>68],
            ['id'=>475,'name'=>'La Paz (Robles)','departament_id'=>20],
            ['id'=>476,'name'=>'La Peña','departament_id'=>25],
            ['id'=>477,'name'=>'La Pintada','departament_id'=>5],
            ['id'=>478,'name'=>'La Plata','departament_id'=>41],
            ['id'=>479,'name'=>'La Playa','departament_id'=>54],
            ['id'=>480,'name'=>'La Primavera','departament_id'=>99],
            ['id'=>481,'name'=>'La Salina','departament_id'=>85],
            ['id'=>482,'name'=>'La Sierra','departament_id'=>19],
            ['id'=>483,'name'=>'La Tebaida','departament_id'=>63],
            ['id'=>484,'name'=>'La Tola','departament_id'=>52],
            ['id'=>485,'name'=>'La Unión','departament_id'=>5],
            ['id'=>486,'name'=>'La Unión','departament_id'=>52],
            ['id'=>487,'name'=>'La Unión','departament_id'=>70],
            ['id'=>488,'name'=>'La Unión','departament_id'=>76],
            ['id'=>489,'name'=>'La Uvita','departament_id'=>15],
            ['id'=>490,'name'=>'La Vega','departament_id'=>19],
            ['id'=>491,'name'=>'La Vega','departament_id'=>25],
            ['id'=>492,'name'=>'La Victoria','departament_id'=>15],
            ['id'=>493,'name'=>'La Victoria','departament_id'=>17],
            ['id'=>494,'name'=>'La Victoria','departament_id'=>76],
            ['id'=>495,'name'=>'La Virginia','departament_id'=>66],
            ['id'=>496,'name'=>'Labateca','departament_id'=>54],
            ['id'=>497,'name'=>'Labranzagrande','departament_id'=>15],
            ['id'=>498,'name'=>'Landázuri','departament_id'=>68],
            ['id'=>499,'name'=>'Lebrija','departament_id'=>68],
            ['id'=>500,'name'=>'Leiva','departament_id'=>52],
            ['id'=>501,'name'=>'Lejanías','departament_id'=>50],
            ['id'=>502,'name'=>'Lenguazaque','departament_id'=>25],
            ['id'=>503,'name'=>'Leticia','departament_id'=>91],
            ['id'=>504,'name'=>'Liborina','departament_id'=>5],
            ['id'=>505,'name'=>'Linares','departament_id'=>52],
            ['id'=>506,'name'=>'Lloró','departament_id'=>27],
            ['id'=>507,'name'=>'Lorica','departament_id'=>23],
            ['id'=>508,'name'=>'Los Córdobas','departament_id'=>23],
            ['id'=>509,'name'=>'Los Palmitos','departament_id'=>70],
            ['id'=>510,'name'=>'Los Patios','departament_id'=>54],
            ['id'=>511,'name'=>'Los Santos','departament_id'=>68],
            ['id'=>512,'name'=>'Lourdes','departament_id'=>54],
            ['id'=>513,'name'=>'Luruaco','departament_id'=>8],
            ['id'=>514,'name'=>'Lérida','departament_id'=>73],
            ['id'=>515,'name'=>'Líbano','departament_id'=>73],
            ['id'=>516,'name'=>'López (Micay)','departament_id'=>19],
            ['id'=>517,'name'=>'Macanal','departament_id'=>15],
            ['id'=>518,'name'=>'Macaravita','departament_id'=>68],
            ['id'=>519,'name'=>'Maceo','departament_id'=>5],
            ['id'=>520,'name'=>'Machetá','departament_id'=>25],
            ['id'=>521,'name'=>'Madrid','departament_id'=>25],
            ['id'=>522,'name'=>'Magangué','departament_id'=>13],
            ['id'=>523,'name'=>'Magüi (Payán)','departament_id'=>52],
            ['id'=>524,'name'=>'Mahates','departament_id'=>13],
            ['id'=>525,'name'=>'Maicao','departament_id'=>44],
            ['id'=>526,'name'=>'Majagual','departament_id'=>70],
            ['id'=>527,'name'=>'Malambo','departament_id'=>8],
            ['id'=>528,'name'=>'Mallama (Piedrancha)','departament_id'=>52],
            ['id'=>529,'name'=>'Manatí','departament_id'=>8],
            ['id'=>530,'name'=>'Manaure','departament_id'=>44],
            ['id'=>531,'name'=>'Manaure Balcón del Cesar','departament_id'=>20],
            ['id'=>532,'name'=>'Manizales','departament_id'=>17],
            ['id'=>533,'name'=>'Manta','departament_id'=>25],
            ['id'=>534,'name'=>'Manzanares','departament_id'=>17],
            ['id'=>535,'name'=>'Maní','departament_id'=>85],
            ['id'=>536,'name'=>'Mapiripan','departament_id'=>50],
            ['id'=>537,'name'=>'Margarita','departament_id'=>13],
            ['id'=>538,'name'=>'Marinilla','departament_id'=>5],
            ['id'=>539,'name'=>'Maripí','departament_id'=>15],
            ['id'=>540,'name'=>'Mariquita','departament_id'=>73],
            ['id'=>541,'name'=>'Marmato','departament_id'=>17],
            ['id'=>542,'name'=>'Marquetalia','departament_id'=>17],
            ['id'=>543,'name'=>'Marsella','departament_id'=>66],
            ['id'=>544,'name'=>'Marulanda','departament_id'=>17],
            ['id'=>545,'name'=>'María la Baja','departament_id'=>13],
            ['id'=>546,'name'=>'Matanza','departament_id'=>68],
            ['id'=>547,'name'=>'Medellín','departament_id'=>5],
            ['id'=>548,'name'=>'Medina','departament_id'=>25],
            ['id'=>549,'name'=>'Medio Atrato','departament_id'=>27],
            ['id'=>550,'name'=>'Medio Baudó','departament_id'=>27],
            ['id'=>551,'name'=>'Medio San Juan (ANDAGOYA)','departament_id'=>27],
            ['id'=>552,'name'=>'Melgar','departament_id'=>73],
            ['id'=>553,'name'=>'Mercaderes','departament_id'=>19],
            ['id'=>554,'name'=>'Mesetas','departament_id'=>50],
            ['id'=>555,'name'=>'Milán','departament_id'=>18],
            ['id'=>556,'name'=>'Miraflores','departament_id'=>15],
            ['id'=>557,'name'=>'Miraflores','departament_id'=>95],
            ['id'=>558,'name'=>'Miranda','departament_id'=>19],
            ['id'=>559,'name'=>'Mistrató','departament_id'=>66],
            ['id'=>560,'name'=>'Mitú','departament_id'=>97],
            ['id'=>561,'name'=>'Mocoa','departament_id'=>86],
            ['id'=>562,'name'=>'Mogotes','departament_id'=>68],
            ['id'=>563,'name'=>'Molagavita','departament_id'=>68],
            ['id'=>564,'name'=>'Momil','departament_id'=>23],
            ['id'=>565,'name'=>'Mompós','departament_id'=>13],
            ['id'=>566,'name'=>'Mongua','departament_id'=>15],
            ['id'=>567,'name'=>'Monguí','departament_id'=>15],
            ['id'=>568,'name'=>'Moniquirá','departament_id'=>15],
            ['id'=>569,'name'=>'Montebello','departament_id'=>5],
            ['id'=>570,'name'=>'Montecristo','departament_id'=>13],
            ['id'=>571,'name'=>'Montelíbano','departament_id'=>23],
            ['id'=>572,'name'=>'Montenegro','departament_id'=>63],
            ['id'=>573,'name'=>'Monteria','departament_id'=>23],
            ['id'=>574,'name'=>'Monterrey','departament_id'=>85],
            ['id'=>575,'name'=>'Morales','departament_id'=>13],
            ['id'=>576,'name'=>'Morales','departament_id'=>19],
            ['id'=>577,'name'=>'Morelia','departament_id'=>18],
            ['id'=>578,'name'=>'Morroa','departament_id'=>70],
            ['id'=>579,'name'=>'Mosquera','departament_id'=>25],
            ['id'=>580,'name'=>'Mosquera','departament_id'=>52],
            ['id'=>581,'name'=>'Motavita','departament_id'=>15],
            ['id'=>582,'name'=>'Moñitos','departament_id'=>23],
            ['id'=>583,'name'=>'Murillo','departament_id'=>73],
            ['id'=>584,'name'=>'Murindó','departament_id'=>5],
            ['id'=>585,'name'=>'Mutatá','departament_id'=>5],
            ['id'=>586,'name'=>'Mutiscua','departament_id'=>54],
            ['id'=>587,'name'=>'Muzo','departament_id'=>15],
            ['id'=>588,'name'=>'Málaga','departament_id'=>68],
            ['id'=>589,'name'=>'Nariño','departament_id'=>5],
            ['id'=>590,'name'=>'Nariño','departament_id'=>25],
            ['id'=>591,'name'=>'Nariño','departament_id'=>52],
            ['id'=>592,'name'=>'Natagaima','departament_id'=>73],
            ['id'=>593,'name'=>'Nechí','departament_id'=>5],
            ['id'=>594,'name'=>'Necoclí','departament_id'=>5],
            ['id'=>595,'name'=>'Neira','departament_id'=>17],
            ['id'=>596,'name'=>'Neiva','departament_id'=>41],
            ['id'=>597,'name'=>'Nemocón','departament_id'=>25],
            ['id'=>598,'name'=>'Nilo','departament_id'=>25],
            ['id'=>599,'name'=>'Nimaima','departament_id'=>25],
            ['id'=>600,'name'=>'Nobsa','departament_id'=>15],
            ['id'=>601,'name'=>'Nocaima','departament_id'=>25],
            ['id'=>602,'name'=>'Norcasia','departament_id'=>17],
            ['id'=>603,'name'=>'Norosí','departament_id'=>13],
            ['id'=>604,'name'=>'Novita','departament_id'=>27],
            ['id'=>605,'name'=>'Nueva Granada','departament_id'=>47],
            ['id'=>606,'name'=>'Nuevo Colón','departament_id'=>15],
            ['id'=>607,'name'=>'Nunchía','departament_id'=>85],
            ['id'=>608,'name'=>'Nuquí','departament_id'=>27],
            ['id'=>609,'name'=>'Nátaga','departament_id'=>41],
            ['id'=>610,'name'=>'Obando','departament_id'=>76],
            ['id'=>611,'name'=>'Ocamonte','departament_id'=>68],
            ['id'=>612,'name'=>'Ocaña','departament_id'=>54],
            ['id'=>613,'name'=>'Oiba','departament_id'=>68],
            ['id'=>614,'name'=>'Oicatá','departament_id'=>15],
            ['id'=>615,'name'=>'Olaya','departament_id'=>5],
            ['id'=>616,'name'=>'Olaya Herrera','departament_id'=>52],
            ['id'=>617,'name'=>'Onzaga','departament_id'=>68],
            ['id'=>618,'name'=>'Oporapa','departament_id'=>41],
            ['id'=>619,'name'=>'Orito','departament_id'=>86],
            ['id'=>620,'name'=>'Orocué','departament_id'=>85],
            ['id'=>621,'name'=>'Ortega','departament_id'=>73],
            ['id'=>622,'name'=>'Ospina','departament_id'=>52],
            ['id'=>623,'name'=>'Otanche','departament_id'=>15],
            ['id'=>624,'name'=>'Ovejas','departament_id'=>70],
            ['id'=>625,'name'=>'Pachavita','departament_id'=>15],
            ['id'=>626,'name'=>'Pacho','departament_id'=>25],
            ['id'=>627,'name'=>'Padilla','departament_id'=>19],
            ['id'=>628,'name'=>'Paicol','departament_id'=>41],
            ['id'=>629,'name'=>'Pailitas','departament_id'=>20],
            ['id'=>630,'name'=>'Paime','departament_id'=>25],
            ['id'=>631,'name'=>'Paipa','departament_id'=>15],
            ['id'=>632,'name'=>'Pajarito','departament_id'=>15],
            ['id'=>633,'name'=>'Palermo','departament_id'=>41],
            ['id'=>634,'name'=>'Palestina','departament_id'=>17],
            ['id'=>635,'name'=>'Palestina','departament_id'=>41],
            ['id'=>636,'name'=>'Palmar','departament_id'=>68],
            ['id'=>637,'name'=>'Palmar de Varela','departament_id'=>8],
            ['id'=>638,'name'=>'Palmas del Socorro','departament_id'=>68],
            ['id'=>639,'name'=>'Palmira','departament_id'=>76],
            ['id'=>640,'name'=>'Palmito','departament_id'=>70],
            ['id'=>641,'name'=>'Palocabildo','departament_id'=>73],
            ['id'=>642,'name'=>'Pamplona','departament_id'=>54],
            ['id'=>643,'name'=>'Pamplonita','departament_id'=>54],
            ['id'=>644,'name'=>'Pandi','departament_id'=>25],
            ['id'=>645,'name'=>'Panqueba','departament_id'=>15],
            ['id'=>646,'name'=>'Paratebueno','departament_id'=>25],
            ['id'=>647,'name'=>'Pasca','departament_id'=>25],
            ['id'=>648,'name'=>'Patía (El Bordo)','departament_id'=>19],
            ['id'=>649,'name'=>'Pauna','departament_id'=>15],
            ['id'=>650,'name'=>'Paya','departament_id'=>15],
            ['id'=>651,'name'=>'Paz de Ariporo','departament_id'=>85],
            ['id'=>652,'name'=>'Paz de Río','departament_id'=>15],
            ['id'=>653,'name'=>'Pedraza','departament_id'=>47],
            ['id'=>654,'name'=>'Pelaya','departament_id'=>20],
            ['id'=>655,'name'=>'Pensilvania','departament_id'=>17],
            ['id'=>656,'name'=>'Peque','departament_id'=>5],
            ['id'=>657,'name'=>'Pereira','departament_id'=>66],
            ['id'=>658,'name'=>'Pesca','departament_id'=>15],
            ['id'=>659,'name'=>'Peñol','departament_id'=>5],
            ['id'=>660,'name'=>'Piamonte','departament_id'=>19],
            ['id'=>661,'name'=>'Pie de Cuesta','departament_id'=>68],
            ['id'=>662,'name'=>'Piedras','departament_id'=>73],
            ['id'=>663,'name'=>'Piendamó','departament_id'=>19],
            ['id'=>664,'name'=>'Pijao','departament_id'=>63],
            ['id'=>665,'name'=>'Pijiño','departament_id'=>47],
            ['id'=>666,'name'=>'Pinchote','departament_id'=>68],
            ['id'=>667,'name'=>'Pinillos','departament_id'=>13],
            ['id'=>668,'name'=>'Piojo','departament_id'=>8],
            ['id'=>669,'name'=>'Pisva','departament_id'=>15],
            ['id'=>670,'name'=>'Pital','departament_id'=>41],
            ['id'=>671,'name'=>'Pitalito','departament_id'=>41],
            ['id'=>672,'name'=>'Pivijay','departament_id'=>47],
            ['id'=>673,'name'=>'Planadas','departament_id'=>73],
            ['id'=>674,'name'=>'Planeta Rica','departament_id'=>23],
            ['id'=>675,'name'=>'Plato','departament_id'=>47],
            ['id'=>676,'name'=>'Policarpa','departament_id'=>52],
            ['id'=>677,'name'=>'Polonuevo','departament_id'=>8],
            ['id'=>678,'name'=>'Ponedera','departament_id'=>8],
            ['id'=>679,'name'=>'Popayán','departament_id'=>19],
            ['id'=>680,'name'=>'Pore','departament_id'=>85],
            ['id'=>681,'name'=>'Potosí','departament_id'=>52],
            ['id'=>682,'name'=>'Pradera','departament_id'=>76],
            ['id'=>683,'name'=>'Prado','departament_id'=>73],
            ['id'=>684,'name'=>'Providencia','departament_id'=>52],
            ['id'=>685,'name'=>'Providencia','departament_id'=>88],
            ['id'=>686,'name'=>'Pueblo Bello','departament_id'=>20],
            ['id'=>687,'name'=>'Pueblo Nuevo','departament_id'=>23],
            ['id'=>688,'name'=>'Pueblo Rico','departament_id'=>66],
            ['id'=>689,'name'=>'Pueblorrico','departament_id'=>5],
            ['id'=>690,'name'=>'Puebloviejo','departament_id'=>47],
            ['id'=>691,'name'=>'Puente Nacional','departament_id'=>68],
            ['id'=>692,'name'=>'Puerres','departament_id'=>52],
            ['id'=>693,'name'=>'Puerto Asís','departament_id'=>86],
            ['id'=>694,'name'=>'Puerto Berrío','departament_id'=>5],
            ['id'=>695,'name'=>'Puerto Boyacá','departament_id'=>15],
            ['id'=>696,'name'=>'Puerto Caicedo','departament_id'=>86],
            ['id'=>697,'name'=>'Puerto Carreño','departament_id'=>99],
            ['id'=>698,'name'=>'Puerto Colombia','departament_id'=>8],
            ['id'=>699,'name'=>'Puerto Concordia','departament_id'=>50],
            ['id'=>700,'name'=>'Puerto Escondido','departament_id'=>23],
            ['id'=>701,'name'=>'Puerto Gaitán','departament_id'=>50],
            ['id'=>702,'name'=>'Puerto Guzmán','departament_id'=>86],
            ['id'=>703,'name'=>'Puerto Leguízamo','departament_id'=>86],
            ['id'=>704,'name'=>'Puerto Libertador','departament_id'=>23],
            ['id'=>705,'name'=>'Puerto Lleras','departament_id'=>50],
            ['id'=>706,'name'=>'Puerto López','departament_id'=>50],
            ['id'=>707,'name'=>'Puerto Nare','departament_id'=>5],
            ['id'=>708,'name'=>'Puerto Nariño','departament_id'=>91],
            ['id'=>709,'name'=>'Puerto Parra','departament_id'=>68],
            ['id'=>710,'name'=>'Puerto Rico','departament_id'=>18],
            ['id'=>711,'name'=>'Puerto Rico','departament_id'=>50],
            ['id'=>712,'name'=>'Puerto Rondón','departament_id'=>81],
            ['id'=>713,'name'=>'Puerto Salgar','departament_id'=>25],
            ['id'=>714,'name'=>'Puerto Santander','departament_id'=>54],
            ['id'=>715,'name'=>'Puerto Tejada','departament_id'=>19],
            ['id'=>716,'name'=>'Puerto Triunfo','departament_id'=>5],
            ['id'=>717,'name'=>'Puerto Wilches','departament_id'=>68],
            ['id'=>718,'name'=>'Pulí','departament_id'=>25],
            ['id'=>719,'name'=>'Pupiales','departament_id'=>52],
            ['id'=>720,'name'=>'Puracé (Coconuco)','departament_id'=>19],
            ['id'=>721,'name'=>'Purificación','departament_id'=>73],
            ['id'=>722,'name'=>'Purísima','departament_id'=>23],
            ['id'=>723,'name'=>'Pácora','departament_id'=>17],
            ['id'=>724,'name'=>'Páez','departament_id'=>15],
            ['id'=>725,'name'=>'Páez (Belalcazar)','departament_id'=>19],
            ['id'=>726,'name'=>'Páramo','departament_id'=>68],
            ['id'=>727,'name'=>'Quebradanegra','departament_id'=>25],
            ['id'=>728,'name'=>'Quetame','departament_id'=>25],
            ['id'=>729,'name'=>'Quibdó','departament_id'=>27],
            ['id'=>730,'name'=>'Quimbaya','departament_id'=>63],
            ['id'=>731,'name'=>'Quinchía','departament_id'=>66],
            ['id'=>732,'name'=>'Quipama','departament_id'=>15],
            ['id'=>733,'name'=>'Quipile','departament_id'=>25],
            ['id'=>734,'name'=>'Ragonvalia','departament_id'=>54],
            ['id'=>735,'name'=>'Ramiriquí','departament_id'=>15],
            ['id'=>736,'name'=>'Recetor','departament_id'=>85],
            ['id'=>737,'name'=>'Regidor','departament_id'=>13],
            ['id'=>738,'name'=>'Remedios','departament_id'=>5],
            ['id'=>739,'name'=>'Remolino','departament_id'=>47],
            ['id'=>740,'name'=>'Repelón','departament_id'=>8],
            ['id'=>741,'name'=>'Restrepo','departament_id'=>50],
            ['id'=>742,'name'=>'Restrepo','departament_id'=>76],
            ['id'=>743,'name'=>'Retiro','departament_id'=>5],
            ['id'=>744,'name'=>'Ricaurte','departament_id'=>25],
            ['id'=>745,'name'=>'Ricaurte','departament_id'=>52],
            ['id'=>746,'name'=>'Rio Negro','departament_id'=>68],
            ['id'=>747,'name'=>'Rioblanco','departament_id'=>73],
            ['id'=>748,'name'=>'Riofrío','departament_id'=>76],
            ['id'=>749,'name'=>'Riohacha','departament_id'=>44],
            ['id'=>750,'name'=>'Risaralda','departament_id'=>17],
            ['id'=>751,'name'=>'Rivera','departament_id'=>41],
            ['id'=>752,'name'=>'Roberto Payán (San José)','departament_id'=>52],
            ['id'=>753,'name'=>'Roldanillo','departament_id'=>76],
            ['id'=>754,'name'=>'Roncesvalles','departament_id'=>73],
            ['id'=>755,'name'=>'Rondón','departament_id'=>15],
            ['id'=>756,'name'=>'Rosas','departament_id'=>19],
            ['id'=>757,'name'=>'Rovira','departament_id'=>73],
            ['id'=>758,'name'=>'Ráquira','departament_id'=>15],
            ['id'=>759,'name'=>'Río Iró','departament_id'=>27],
            ['id'=>760,'name'=>'Río Quito','departament_id'=>27],
            ['id'=>761,'name'=>'Río Sucio','departament_id'=>17],
            ['id'=>762,'name'=>'Río Viejo','departament_id'=>13],
            ['id'=>763,'name'=>'Río de oro','departament_id'=>20],
            ['id'=>764,'name'=>'Ríonegro','departament_id'=>5],
            ['id'=>765,'name'=>'Ríosucio','departament_id'=>27],
            ['id'=>766,'name'=>'Sabana de Torres','departament_id'=>68],
            ['id'=>767,'name'=>'Sabanagrande','departament_id'=>8],
            ['id'=>768,'name'=>'Sabanalarga','departament_id'=>5],
            ['id'=>769,'name'=>'Sabanalarga','departament_id'=>8],
            ['id'=>770,'name'=>'Sabanalarga','departament_id'=>85],
            ['id'=>771,'name'=>'Sabanas de San Angel (SAN ANGEL)','departament_id'=>47],
            ['id'=>772,'name'=>'Sabaneta','departament_id'=>5],
            ['id'=>773,'name'=>'Saboyá','departament_id'=>15],
            ['id'=>774,'name'=>'Sahagún','departament_id'=>23],
            ['id'=>775,'name'=>'Saladoblanco','departament_id'=>41],
            ['id'=>776,'name'=>'Salamina','departament_id'=>17],
            ['id'=>777,'name'=>'Salamina','departament_id'=>47],
            ['id'=>778,'name'=>'Salazar','departament_id'=>54],
            ['id'=>779,'name'=>'Saldaña','departament_id'=>73],
            ['id'=>780,'name'=>'Salento','departament_id'=>63],
            ['id'=>781,'name'=>'Salgar','departament_id'=>5],
            ['id'=>782,'name'=>'Samacá','departament_id'=>15],
            ['id'=>783,'name'=>'Samaniego','departament_id'=>52],
            ['id'=>784,'name'=>'Samaná','departament_id'=>17],
            ['id'=>785,'name'=>'Sampués','departament_id'=>70],
            ['id'=>786,'name'=>'San Agustín','departament_id'=>41],
            ['id'=>787,'name'=>'San Alberto','departament_id'=>20],
            ['id'=>788,'name'=>'San Andrés','departament_id'=>68],
            ['id'=>789,'name'=>'San Andrés Sotavento','departament_id'=>23],
            ['id'=>790,'name'=>'San Andrés de Cuerquía','departament_id'=>5],
            ['id'=>791,'name'=>'San Antero','departament_id'=>23],
            ['id'=>792,'name'=>'San Antonio','departament_id'=>73],
            ['id'=>793,'name'=>'San Antonio de Tequendama','departament_id'=>25],
            ['id'=>794,'name'=>'San Benito','departament_id'=>68],
            ['id'=>795,'name'=>'San Benito Abad','departament_id'=>70],
            ['id'=>796,'name'=>'San Bernardo','departament_id'=>25],
            ['id'=>797,'name'=>'San Bernardo','departament_id'=>52],
            ['id'=>798,'name'=>'San Bernardo del Viento','departament_id'=>23],
            ['id'=>799,'name'=>'San Calixto','departament_id'=>54],
            ['id'=>800,'name'=>'San Carlos','departament_id'=>5],
            ['id'=>801,'name'=>'San Carlos','departament_id'=>23],
            ['id'=>802,'name'=>'San Carlos de Guaroa','departament_id'=>50],
            ['id'=>803,'name'=>'San Cayetano','departament_id'=>25],
            ['id'=>804,'name'=>'San Cayetano','departament_id'=>54],
            ['id'=>805,'name'=>'San Cristobal','departament_id'=>13],
            ['id'=>806,'name'=>'San Diego','departament_id'=>20],
            ['id'=>807,'name'=>'San Eduardo','departament_id'=>15],
            ['id'=>808,'name'=>'San Estanislao','departament_id'=>13],
            ['id'=>809,'name'=>'San Fernando','departament_id'=>13],
            ['id'=>810,'name'=>'San Francisco','departament_id'=>5],
            ['id'=>811,'name'=>'San Francisco','departament_id'=>25],
            ['id'=>812,'name'=>'San Francisco','departament_id'=>86],
            ['id'=>813,'name'=>'San Gíl','departament_id'=>68],
            ['id'=>814,'name'=>'San Jacinto','departament_id'=>13],
            ['id'=>815,'name'=>'San Jacinto del Cauca','departament_id'=>13],
            ['id'=>816,'name'=>'San Jerónimo','departament_id'=>5],
            ['id'=>817,'name'=>'San Joaquín','departament_id'=>68],
            ['id'=>818,'name'=>'San José','departament_id'=>17],
            ['id'=>819,'name'=>'San José de Miranda','departament_id'=>68],
            ['id'=>820,'name'=>'San José de Montaña','departament_id'=>5],
            ['id'=>821,'name'=>'San José de Pare','departament_id'=>15],
            ['id'=>822,'name'=>'San José de Uré','departament_id'=>23],
            ['id'=>823,'name'=>'San José del Fragua','departament_id'=>18],
            ['id'=>824,'name'=>'San José del Guaviare','departament_id'=>95],
            ['id'=>825,'name'=>'San José del Palmar','departament_id'=>27],
            ['id'=>826,'name'=>'San Juan de Arama','departament_id'=>50],
            ['id'=>827,'name'=>'San Juan de Betulia','departament_id'=>70],
            ['id'=>828,'name'=>'San Juan de Nepomuceno','departament_id'=>13],
            ['id'=>829,'name'=>'San Juan de Pasto','departament_id'=>52],
            ['id'=>830,'name'=>'San Juan de Río Seco','departament_id'=>25],
            ['id'=>831,'name'=>'San Juan de Urabá','departament_id'=>5],
            ['id'=>832,'name'=>'San Juan del Cesar','departament_id'=>44],
            ['id'=>833,'name'=>'San Juanito','departament_id'=>50],
            ['id'=>834,'name'=>'San Lorenzo','departament_id'=>52],
            ['id'=>835,'name'=>'San Luis','departament_id'=>73],
            ['id'=>836,'name'=>'San Luís','departament_id'=>5],
            ['id'=>837,'name'=>'San Luís de Gaceno','departament_id'=>15],
            ['id'=>838,'name'=>'San Luís de Palenque','departament_id'=>85],
            ['id'=>839,'name'=>'San Marcos','departament_id'=>70],
            ['id'=>840,'name'=>'San Martín','departament_id'=>20],
            ['id'=>841,'name'=>'San Martín','departament_id'=>50],
            ['id'=>842,'name'=>'San Martín de Loba','departament_id'=>13],
            ['id'=>843,'name'=>'San Mateo','departament_id'=>15],
            ['id'=>844,'name'=>'San Miguel','departament_id'=>68],
            ['id'=>845,'name'=>'San Miguel','departament_id'=>86],
            ['id'=>846,'name'=>'San Miguel de Sema','departament_id'=>15],
            ['id'=>847,'name'=>'San Onofre','departament_id'=>70],
            ['id'=>848,'name'=>'San Pablo','departament_id'=>13],
            ['id'=>849,'name'=>'San Pablo','departament_id'=>52],
            ['id'=>850,'name'=>'San Pablo de Borbur','departament_id'=>15],
            ['id'=>851,'name'=>'San Pedro','departament_id'=>5],
            ['id'=>852,'name'=>'San Pedro','departament_id'=>70],
            ['id'=>853,'name'=>'San Pedro','departament_id'=>76],
            ['id'=>854,'name'=>'San Pedro de Cartago','departament_id'=>52],
            ['id'=>855,'name'=>'San Pedro de Urabá','departament_id'=>5],
            ['id'=>856,'name'=>'San Pelayo','departament_id'=>23],
            ['id'=>857,'name'=>'San Rafael','departament_id'=>5],
            ['id'=>858,'name'=>'San Roque','departament_id'=>5],
            ['id'=>859,'name'=>'San Sebastián','departament_id'=>19],
            ['id'=>860,'name'=>'San Sebastián de Buenavista','departament_id'=>47],
            ['id'=>861,'name'=>'San Vicente','departament_id'=>5],
            ['id'=>862,'name'=>'San Vicente del Caguán','departament_id'=>18],
            ['id'=>863,'name'=>'San Vicente del Chucurí','departament_id'=>68],
            ['id'=>864,'name'=>'San Zenón','departament_id'=>47],
            ['id'=>865,'name'=>'Sandoná','departament_id'=>52],
            ['id'=>866,'name'=>'Santa Ana','departament_id'=>47],
            ['id'=>867,'name'=>'Santa Bárbara','departament_id'=>5],
            ['id'=>868,'name'=>'Santa Bárbara','departament_id'=>68],
            ['id'=>869,'name'=>'Santa Bárbara (Iscuandé)','departament_id'=>52],
            ['id'=>870,'name'=>'Santa Bárbara de Pinto','departament_id'=>47],
            ['id'=>871,'name'=>'Santa Catalina','departament_id'=>13],
            ['id'=>872,'name'=>'Santa Fé de Antioquia','departament_id'=>5],
            ['id'=>873,'name'=>'Santa Genoveva de Docorodó','departament_id'=>27],
            ['id'=>874,'name'=>'Santa Helena del Opón','departament_id'=>68],
            ['id'=>875,'name'=>'Santa Isabel','departament_id'=>73],
            ['id'=>876,'name'=>'Santa Lucía','departament_id'=>8],
            ['id'=>877,'name'=>'Santa Marta','departament_id'=>47],
            ['id'=>878,'name'=>'Santa María','departament_id'=>15],
            ['id'=>879,'name'=>'Santa María','departament_id'=>41],
            ['id'=>880,'name'=>'Santa Rosa','departament_id'=>13],
            ['id'=>881,'name'=>'Santa Rosa','departament_id'=>19],
            ['id'=>882,'name'=>'Santa Rosa de Cabal','departament_id'=>66],
            ['id'=>883,'name'=>'Santa Rosa de Osos','departament_id'=>5],
            ['id'=>884,'name'=>'Santa Rosa de Viterbo','departament_id'=>15],
            ['id'=>885,'name'=>'Santa Rosa del Sur','departament_id'=>13],
            ['id'=>886,'name'=>'Santa Rosalía','departament_id'=>99],
            ['id'=>887,'name'=>'Santa Sofía','departament_id'=>15],
            ['id'=>888,'name'=>'Santana','departament_id'=>15],
            ['id'=>889,'name'=>'Santander de Quilichao','departament_id'=>19],
            ['id'=>890,'name'=>'Santiago','departament_id'=>54],
            ['id'=>891,'name'=>'Santiago','departament_id'=>86],
            ['id'=>892,'name'=>'Santo Domingo','departament_id'=>5],
            ['id'=>893,'name'=>'Santo Tomás','departament_id'=>8],
            ['id'=>894,'name'=>'Santuario','departament_id'=>5],
            ['id'=>895,'name'=>'Santuario','departament_id'=>66],
            ['id'=>896,'name'=>'Sapuyes','departament_id'=>52],
            ['id'=>897,'name'=>'Saravena','departament_id'=>81],
            ['id'=>898,'name'=>'Sardinata','departament_id'=>54],
            ['id'=>899,'name'=>'Sasaima','departament_id'=>25],
            ['id'=>900,'name'=>'Sativanorte','departament_id'=>15],
            ['id'=>901,'name'=>'Sativasur','departament_id'=>15],
            ['id'=>902,'name'=>'Segovia','departament_id'=>5],
            ['id'=>903,'name'=>'Sesquilé','departament_id'=>25],
            ['id'=>904,'name'=>'Sevilla','departament_id'=>76],
            ['id'=>905,'name'=>'Siachoque','departament_id'=>15],
            ['id'=>906,'name'=>'Sibaté','departament_id'=>25],
            ['id'=>907,'name'=>'Sibundoy','departament_id'=>86],
            ['id'=>908,'name'=>'Silos','departament_id'=>54],
            ['id'=>909,'name'=>'Silvania','departament_id'=>25],
            ['id'=>910,'name'=>'Silvia','departament_id'=>19],
            ['id'=>911,'name'=>'Simacota','departament_id'=>68],
            ['id'=>912,'name'=>'Simijaca','departament_id'=>25],
            ['id'=>913,'name'=>'Simití','departament_id'=>13],
            ['id'=>914,'name'=>'Sincelejo','departament_id'=>70],
            ['id'=>915,'name'=>'Sincé','departament_id'=>70],
            ['id'=>916,'name'=>'Sipí','departament_id'=>27],
            ['id'=>917,'name'=>'Sitionuevo','departament_id'=>47],
            ['id'=>918,'name'=>'Soacha','departament_id'=>25],
            ['id'=>919,'name'=>'Soatá','departament_id'=>15],
            ['id'=>920,'name'=>'Socha','departament_id'=>15],
            ['id'=>921,'name'=>'Socorro','departament_id'=>68],
            ['id'=>922,'name'=>'Socotá','departament_id'=>15],
            ['id'=>923,'name'=>'Sogamoso','departament_id'=>15],
            ['id'=>924,'name'=>'Solano','departament_id'=>18],
            ['id'=>925,'name'=>'Soledad','departament_id'=>8],
            ['id'=>926,'name'=>'Solita','departament_id'=>18],
            ['id'=>927,'name'=>'Somondoco','departament_id'=>15],
            ['id'=>928,'name'=>'Sonsón','departament_id'=>5],
            ['id'=>929,'name'=>'Sopetrán','departament_id'=>5],
            ['id'=>930,'name'=>'Soplaviento','departament_id'=>13],
            ['id'=>931,'name'=>'Sopó','departament_id'=>25],
            ['id'=>932,'name'=>'Sora','departament_id'=>15],
            ['id'=>933,'name'=>'Soracá','departament_id'=>15],
            ['id'=>934,'name'=>'Sotaquirá','departament_id'=>15],
            ['id'=>935,'name'=>'Sotara (Paispamba)','departament_id'=>19],
            ['id'=>936,'name'=>'Sotomayor (Los Andes)','departament_id'=>52],
            ['id'=>937,'name'=>'Suaita','departament_id'=>68],
            ['id'=>938,'name'=>'Suan','departament_id'=>8],
            ['id'=>939,'name'=>'Suaza','departament_id'=>41],
            ['id'=>940,'name'=>'Subachoque','departament_id'=>25],
            ['id'=>941,'name'=>'Sucre','departament_id'=>19],
            ['id'=>942,'name'=>'Sucre','departament_id'=>68],
            ['id'=>943,'name'=>'Sucre','departament_id'=>70],
            ['id'=>944,'name'=>'Suesca','departament_id'=>25],
            ['id'=>945,'name'=>'Supatá','departament_id'=>25],
            ['id'=>946,'name'=>'Supía','departament_id'=>17],
            ['id'=>947,'name'=>'Suratá','departament_id'=>68],
            ['id'=>948,'name'=>'Susa','departament_id'=>25],
            ['id'=>949,'name'=>'Susacón','departament_id'=>15],
            ['id'=>950,'name'=>'Sutamarchán','departament_id'=>15],
            ['id'=>951,'name'=>'Sutatausa','departament_id'=>25],
            ['id'=>952,'name'=>'Sutatenza','departament_id'=>15],
            ['id'=>953,'name'=>'Suárez','departament_id'=>19],
            ['id'=>954,'name'=>'Suárez','departament_id'=>73],
            ['id'=>955,'name'=>'Sácama','departament_id'=>85],
            ['id'=>956,'name'=>'Sáchica','departament_id'=>15],
            ['id'=>957,'name'=>'Tabio','departament_id'=>25],
            ['id'=>958,'name'=>'Tadó','departament_id'=>27],
            ['id'=>959,'name'=>'Talaigua Nuevo','departament_id'=>13],
            ['id'=>960,'name'=>'Tamalameque','departament_id'=>20],
            ['id'=>961,'name'=>'Tame','departament_id'=>81],
            ['id'=>962,'name'=>'Taminango','departament_id'=>52],
            ['id'=>963,'name'=>'Tangua','departament_id'=>52],
            ['id'=>964,'name'=>'Taraira','departament_id'=>97],
            ['id'=>965,'name'=>'Tarazá','departament_id'=>5],
            ['id'=>966,'name'=>'Tarqui','departament_id'=>41],
            ['id'=>967,'name'=>'Tarso','departament_id'=>5],
            ['id'=>968,'name'=>'Tasco','departament_id'=>15],
            ['id'=>969,'name'=>'Tauramena','departament_id'=>85],
            ['id'=>970,'name'=>'Tausa','departament_id'=>25],
            ['id'=>971,'name'=>'Tello','departament_id'=>41],
            ['id'=>972,'name'=>'Tena','departament_id'=>25],
            ['id'=>973,'name'=>'Tenerife','departament_id'=>47],
            ['id'=>974,'name'=>'Tenjo','departament_id'=>25],
            ['id'=>975,'name'=>'Tenza','departament_id'=>15],
            ['id'=>976,'name'=>'Teorama','departament_id'=>54],
            ['id'=>977,'name'=>'Teruel','departament_id'=>41],
            ['id'=>978,'name'=>'Tesalia','departament_id'=>41],
            ['id'=>979,'name'=>'Tibacuy','departament_id'=>25],
            ['id'=>980,'name'=>'Tibaná','departament_id'=>15],
            ['id'=>981,'name'=>'Tibasosa','departament_id'=>15],
            ['id'=>982,'name'=>'Tibirita','departament_id'=>25],
            ['id'=>983,'name'=>'Tibú','departament_id'=>54],
            ['id'=>984,'name'=>'Tierralta','departament_id'=>23],
            ['id'=>985,'name'=>'Timaná','departament_id'=>41],
            ['id'=>986,'name'=>'Timbiquí','departament_id'=>19],
            ['id'=>987,'name'=>'Timbío','departament_id'=>19],
            ['id'=>988,'name'=>'Tinjacá','departament_id'=>15],
            ['id'=>989,'name'=>'Tipacoque','departament_id'=>15],
            ['id'=>990,'name'=>'Tiquisio (Puerto Rico)','departament_id'=>13],
            ['id'=>991,'name'=>'Titiribí','departament_id'=>5],
            ['id'=>992,'name'=>'Toca','departament_id'=>15],
            ['id'=>993,'name'=>'Tocaima','departament_id'=>25],
            ['id'=>994,'name'=>'Tocancipá','departament_id'=>25],
            ['id'=>995,'name'=>'Toguí','departament_id'=>15],
            ['id'=>996,'name'=>'Toledo','departament_id'=>5],
            ['id'=>997,'name'=>'Toledo','departament_id'=>54],
            ['id'=>998,'name'=>'Tolú','departament_id'=>70],
            ['id'=>999,'name'=>'Tolú Viejo','departament_id'=>70],
            ['id'=>1000,'name'=>'Tona','departament_id'=>68],
            ['id'=>1001,'name'=>'Topagá','departament_id'=>15],
            ['id'=>1002,'name'=>'Topaipí','departament_id'=>25],
            ['id'=>1003,'name'=>'Toribío','departament_id'=>19],
            ['id'=>1004,'name'=>'Toro','departament_id'=>76],
            ['id'=>1005,'name'=>'Tota','departament_id'=>15],
            ['id'=>1006,'name'=>'Totoró','departament_id'=>19],
            ['id'=>1007,'name'=>'Trinidad','departament_id'=>85],
            ['id'=>1008,'name'=>'Trujillo','departament_id'=>76],
            ['id'=>1009,'name'=>'Tubará','departament_id'=>8],
            ['id'=>1010,'name'=>'Tuchín','departament_id'=>23],
            ['id'=>1011,'name'=>'Tulúa','departament_id'=>76],
            ['id'=>1012,'name'=>'Tumaco','departament_id'=>52],
            ['id'=>1013,'name'=>'Tunja','departament_id'=>15],
            ['id'=>1014,'name'=>'Tunungua','departament_id'=>15],
            ['id'=>1015,'name'=>'Turbaco','departament_id'=>13],
            ['id'=>1016,'name'=>'Turbaná','departament_id'=>13],
            ['id'=>1017,'name'=>'Turbo','departament_id'=>5],
            ['id'=>1018,'name'=>'Turmequé','departament_id'=>15],
            ['id'=>1019,'name'=>'Tuta','departament_id'=>15],
            ['id'=>1020,'name'=>'Tutasá','departament_id'=>15],
            ['id'=>1021,'name'=>'Támara','departament_id'=>85],
            ['id'=>1022,'name'=>'Támesis','departament_id'=>5],
            ['id'=>1023,'name'=>'Túquerres','departament_id'=>52],
            ['id'=>1024,'name'=>'Ubalá','departament_id'=>25],
            ['id'=>1025,'name'=>'Ubaque','departament_id'=>25],
            ['id'=>1026,'name'=>'Ubaté','departament_id'=>25],
            ['id'=>1027,'name'=>'Ulloa','departament_id'=>76],
            ['id'=>1028,'name'=>'Une','departament_id'=>25],
            ['id'=>1029,'name'=>'Unguía','departament_id'=>27],
            ['id'=>1030,'name'=>'Unión Panamericana (ÁNIMAS)','departament_id'=>27],
            ['id'=>1031,'name'=>'Uramita','departament_id'=>5],
            ['id'=>1032,'name'=>'Uribe','departament_id'=>50],
            ['id'=>1033,'name'=>'Uribia','departament_id'=>44],
            ['id'=>1034,'name'=>'Urrao','departament_id'=>5],
            ['id'=>1035,'name'=>'Urumita','departament_id'=>44],
            ['id'=>1036,'name'=>'Usiacuri','departament_id'=>8],
            ['id'=>1037,'name'=>'Valdivia','departament_id'=>5],
            ['id'=>1038,'name'=>'Valencia','departament_id'=>23],
            ['id'=>1039,'name'=>'Valle de San José','departament_id'=>68],
            ['id'=>1040,'name'=>'Valle de San Juan','departament_id'=>73],
            ['id'=>1041,'name'=>'Valle del Guamuez','departament_id'=>86],
            ['id'=>1042,'name'=>'Valledupar','departament_id'=>20],
            ['id'=>1043,'name'=>'Valparaiso','departament_id'=>5],
            ['id'=>1044,'name'=>'Valparaiso','departament_id'=>18],
            ['id'=>1045,'name'=>'Vegachí','departament_id'=>5],
            ['id'=>1046,'name'=>'Venadillo','departament_id'=>73],
            ['id'=>1047,'name'=>'Venecia','departament_id'=>5],
            ['id'=>1048,'name'=>'Venecia (Ospina Pérez)','departament_id'=>25],
            ['id'=>1049,'name'=>'Ventaquemada','departament_id'=>15],
            ['id'=>1050,'name'=>'Vergara','departament_id'=>25],
            ['id'=>1051,'name'=>'Versalles','departament_id'=>76],
            ['id'=>1052,'name'=>'Vetas','departament_id'=>68],
            ['id'=>1053,'name'=>'Viani','departament_id'=>25],
            ['id'=>1054,'name'=>'Vigía del Fuerte','departament_id'=>5],
            ['id'=>1055,'name'=>'Vijes','departament_id'=>76],
            ['id'=>1056,'name'=>'Villa Caro','departament_id'=>54],
            ['id'=>1057,'name'=>'Villa Rica','departament_id'=>19],
            ['id'=>1058,'name'=>'Villa de Leiva','departament_id'=>15],
            ['id'=>1059,'name'=>'Villa del Rosario','departament_id'=>54],
            ['id'=>1060,'name'=>'Villagarzón','departament_id'=>86],
            ['id'=>1061,'name'=>'Villagómez','departament_id'=>25],
            ['id'=>1062,'name'=>'Villahermosa','departament_id'=>73],
            ['id'=>1063,'name'=>'Villamaría','departament_id'=>17],
            ['id'=>1064,'name'=>'Villanueva','departament_id'=>13],
            ['id'=>1065,'name'=>'Villanueva','departament_id'=>44],
            ['id'=>1066,'name'=>'Villanueva','departament_id'=>68],
            ['id'=>1067,'name'=>'Villanueva','departament_id'=>85],
            ['id'=>1068,'name'=>'Villapinzón','departament_id'=>25],
            ['id'=>1069,'name'=>'Villarrica','departament_id'=>73],
            ['id'=>1070,'name'=>'Villavicencio','departament_id'=>50],
            ['id'=>1071,'name'=>'Villavieja','departament_id'=>41],
            ['id'=>1072,'name'=>'Villeta','departament_id'=>25],
            ['id'=>1073,'name'=>'Viotá','departament_id'=>25],
            ['id'=>1074,'name'=>'Viracachá','departament_id'=>15],
            ['id'=>1075,'name'=>'Vista Hermosa','departament_id'=>50],
            ['id'=>1076,'name'=>'Viterbo','departament_id'=>17],
            ['id'=>1077,'name'=>'Vélez','departament_id'=>68],
            ['id'=>1078,'name'=>'Yacopí','departament_id'=>25],
            ['id'=>1079,'name'=>'Yacuanquer','departament_id'=>52],
            ['id'=>1080,'name'=>'Yaguará','departament_id'=>41],
            ['id'=>1081,'name'=>'Yalí','departament_id'=>5],
            ['id'=>1082,'name'=>'Yarumal','departament_id'=>5],
            ['id'=>1083,'name'=>'Yolombó','departament_id'=>5],
            ['id'=>1084,'name'=>'Yondó (Casabe)','departament_id'=>5],
            ['id'=>1085,'name'=>'Yopal','departament_id'=>85],
            ['id'=>1086,'name'=>'Yotoco','departament_id'=>76],
            ['id'=>1087,'name'=>'Yumbo','departament_id'=>76],
            ['id'=>1088,'name'=>'Zambrano','departament_id'=>13],
            ['id'=>1089,'name'=>'Zapatoca','departament_id'=>68],
            ['id'=>1090,'name'=>'Zapayán (PUNTA DE PIEDRAS)','departament_id'=>47],
            ['id'=>1091,'name'=>'Zaragoza','departament_id'=>5],
            ['id'=>1092,'name'=>'Zarzal','departament_id'=>76],
            ['id'=>1093,'name'=>'Zetaquirá','departament_id'=>15],
            ['id'=>1094,'name'=>'Zipacón','departament_id'=>25],
            ['id'=>1095,'name'=>'Zipaquirá','departament_id'=>25],
            ['id'=>1096,'name'=>'Zona Bananera (PRADO - SEVILLA)','departament_id'=>47],
            ['id'=>1097,'name'=>'Ábrego','departament_id'=>54],
            ['id'=>1098,'name'=>'Íquira','departament_id'=>41],
            ['id'=>1099,'name'=>'Úmbita','departament_id'=>15],
            ['id'=>1100,'name'=>'Útica','departament_id'=>25],
        ];
        foreach ($arrayData as $key => $value) {
            $data = new Citie();
            $data->id =  $value["id"];
            $data->name =  $value["name"];
            $data->departament_id =  $value["departament_id"];
            $data->save();
        }
    }
}
