<?php

namespace Database\Seeders;

use App\Models\LedgerAccountSubAccount;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LedgerAccountSubAccountSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $arrayData=[
            [
                "id"=>1,
                "code"=>110505,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>1,
                "ledgerAccountAccount_id"=>1,
                "name"=>"Caja General",
            ],            
            [
                "id"=>2,
                "code"=>110510,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>1,
                "ledgerAccountAccount_id"=>1,
                "name"=>"Cajas menores",
            ],            
            [
                "id"=>3,
                "code"=>111005,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>1,
                "ledgerAccountAccount_id"=>2,
                "name"=>"Moneda nacional",
            ],            
            [
                "id"=>4,
                "code"=>112005,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>1,
                "ledgerAccountAccount_id"=>3,
                "name"=>"Bancos",
            ],            
            [
                "id"=>5,
                "code"=>114505,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>1,
                "ledgerAccountAccount_id"=>4,
                "name"=>"Fiducias",
            ],            
            [
                "id"=>6,
                "code"=>120535,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>2,
                "ledgerAccountAccount_id"=>5,
                "name"=>"Comercio al por mayor y al por menor",
            ],            
            [
                "id"=>7,
                "code"=>129515,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>2,
                "ledgerAccountAccount_id"=>6,
                "name"=>"Acciones o derechos en clubes deportivos",
            ],            
            [
                "id"=>8,
                "code"=>129595,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>2,
                "ledgerAccountAccount_id"=>6,
                "name"=>"Otras inversiones",
            ],            
            [
                "id"=>9,
                "code"=>130505,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>3,
                "ledgerAccountAccount_id"=>7,
                "name"=>"Clientes nacionales",
            ],            
            [
                "id"=>10,
                "code"=>130510,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>3,
                "ledgerAccountAccount_id"=>7,
                "name"=>"Clientes del exterior",
            ],            
            [
                "id"=>11,
                "code"=>132510,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>3,
                "ledgerAccountAccount_id"=>8,
                "name"=>"A accionistas",
            ],            
            [
                "id"=>12,
                "code"=>133005,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>3,
                "ledgerAccountAccount_id"=>9,
                "name"=>"A proveedores",
            ],            
            [
                "id"=>13,
                "code"=>133010,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>3,
                "ledgerAccountAccount_id"=>9,
                "name"=>"A contratistas",
            ],            
            [
                "id"=>14,
                "code"=>133015,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>3,
                "ledgerAccountAccount_id"=>9,
                "name"=>"A trabajadores",
            ],            
            [
                "id"=>15,
                "code"=>133095,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>3,
                "ledgerAccountAccount_id"=>9,
                "name"=>"Otros",
            ],            
            [
                "id"=>16,
                "code"=>135510,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>3,
                "ledgerAccountAccount_id"=>10,
                "name"=>"Anticipos de impuestos de industria y com.",
            ],            
            [
                "id"=>17,
                "code"=>135515,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>3,
                "ledgerAccountAccount_id"=>10,
                "name"=>"Anticipos Retención en la fuente",
            ],            
            [
                "id"=>18,
                "code"=>135517,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>3,
                "ledgerAccountAccount_id"=>10,
                "name"=>"Impuesto a las ventas retenido",
            ],            
            [
                "id"=>19,
                "code"=>135518,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>3,
                "ledgerAccountAccount_id"=>10,
                "name"=>"Impuesto de industria y comercio retenido",
            ],            
            [
                "id"=>20,
                "code"=>136515,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>3,
                "ledgerAccountAccount_id"=>11,
                "name"=>"Educación",
            ],            
            [
                "id"=>21,
                "code"=>136525,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>3,
                "ledgerAccountAccount_id"=>11,
                "name"=>"Calamidad domestica",
            ],            
            [
                "id"=>22,
                "code"=>138095,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>3,
                "ledgerAccountAccount_id"=>12,
                "name"=>"Otros",
            ],            
            [
                "id"=>23,
                "code"=>139905,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>3,
                "ledgerAccountAccount_id"=>13,
                "name"=>"Clientes",
            ],            
            [
                "id"=>24,
                "code"=>142079,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>4,
                "ledgerAccountAccount_id"=>14,
                "name"=>"Fabricación de partes piezas y accesorios para aut",
            ],            
            [
                "id"=>25,
                "code"=>143501,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>4,
                "ledgerAccountAccount_id"=>15,
                "name"=>"Mercancías no fabricadas",
            ],            
            [
                "id"=>26,
                "code"=>149801,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>4,
                "ledgerAccountAccount_id"=>16,
                "name"=>"Otros",
            ],            
            [
                "id"=>27,
                "code"=>150405,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>5,
                "ledgerAccountAccount_id"=>17,
                "name"=>"Urbanos",
            ],            
            [
                "id"=>28,
                "code"=>151605,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>5,
                "ledgerAccountAccount_id"=>18,
                "name"=>"Edificios",
            ],            
            [
                "id"=>29,
                "code"=>151610,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>5,
                "ledgerAccountAccount_id"=>18,
                "name"=>"Edificios",
            ],            
            [
                "id"=>30,
                "code"=>152405,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>5,
                "ledgerAccountAccount_id"=>19,
                "name"=>"Muebles y enseres",
            ],            
            [
                "id"=>31,
                "code"=>152410,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>5,
                "ledgerAccountAccount_id"=>19,
                "name"=>"Equipos",
            ],            
            [
                "id"=>32,
                "code"=>152805,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>5,
                "ledgerAccountAccount_id"=>20,
                "name"=>"Equipos de procesamiento de datos",
            ],            
            [
                "id"=>33,
                "code"=>154005,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>5,
                "ledgerAccountAccount_id"=>21,
                "name"=>"Vehículos en leasing",
            ],            
            [
                "id"=>34,
                "code"=>159205,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>5,
                "ledgerAccountAccount_id"=>22,
                "name"=>"Construcciones y edificaciones",
            ],            
            [
                "id"=>35,
                "code"=>159215,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>5,
                "ledgerAccountAccount_id"=>22,
                "name"=>"Equipo de oficiona",
            ],            
            [
                "id"=>36,
                "code"=>159220,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>5,
                "ledgerAccountAccount_id"=>22,
                "name"=>"Equipo de computación y comunicación",
            ],            
            [
                "id"=>37,
                "code"=>159235,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>5,
                "ledgerAccountAccount_id"=>22,
                "name"=>"Flota y equipo de transporte",
            ],            
            [
                "id"=>38,
                "code"=>163501,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>6,
                "ledgerAccountAccount_id"=>23,
                "name"=>"Derecho de uso",
            ],            
            [
                "id"=>39,
                "code"=>163515,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>6,
                "ledgerAccountAccount_id"=>23,
                "name"=>"Marca adquirida",
            ],            
            [
                "id"=>40,
                "code"=>172020,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>7,
                "ledgerAccountAccount_id"=>24,
                "name"=>"Negocios conjuntos",
            ],            
            [
                "id"=>41,
                "code"=>180505,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>8,
                "ledgerAccountAccount_id"=>25,
                "name"=>"Renta y complementarios",
            ],            
            [
                "id"=>42,
                "code"=>194510,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>9,
                "ledgerAccountAccount_id"=>26,
                "name"=>"De inversiones",
            ],            
            [
                "id"=>43,
                "code"=>210510,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>10,
                "ledgerAccountAccount_id"=>27,
                "name"=>"Pagares",
            ],            
            [
                "id"=>44,
                "code"=>211095,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>10,
                "ledgerAccountAccount_id"=>28,
                "name"=>"Otros",
            ],            
            [
                "id"=>45,
                "code"=>220505,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>11,
                "ledgerAccountAccount_id"=>29,
                "name"=>"Proveedores nacionales",
            ],            
            [
                "id"=>46,
                "code"=>221005,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>11,
                "ledgerAccountAccount_id"=>30,
                "name"=>"Proveeodres del exterior",
            ],            
            [
                "id"=>47,
                "code"=>230505,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "ledgerAccountAccount_id"=>31,
                "name"=>"Cuentas corrientes comerciales",
            ],            
            [
                "id"=>48,
                "code"=>233525,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "ledgerAccountAccount_id"=>32,
                "name"=>"Honorarios",
            ],            
            [
                "id"=>49,
                "code"=>233595,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "ledgerAccountAccount_id"=>32,
                "name"=>"Otros",
            ],            
            [
                "id"=>50,
                "code"=>236505,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "ledgerAccountAccount_id"=>33,
                "name"=>"Salarios y pagos laborales",
            ],            
            [
                "id"=>51,
                "code"=>236510,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "ledgerAccountAccount_id"=>33,
                "name"=>"Dividendos y/o participaciones",
            ],            
            [
                "id"=>52,
                "code"=>236515,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "ledgerAccountAccount_id"=>33,
                "name"=>"Honorarios",
            ],            
            [
                "id"=>53,
                "code"=>236520,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "ledgerAccountAccount_id"=>33,
                "name"=>"Comisiones",
            ],            
            [
                "id"=>54,
                "code"=>236525,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "ledgerAccountAccount_id"=>33,
                "name"=>"Servicios",
            ],            
            [
                "id"=>55,
                "code"=>236530,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "ledgerAccountAccount_id"=>33,
                "name"=>"Arrendamientos",
            ],            
            [
                "id"=>56,
                "code"=>236535,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "ledgerAccountAccount_id"=>33,
                "name"=>"Rendimientos financieros",
            ],            
            [
                "id"=>57,
                "code"=>236540,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "ledgerAccountAccount_id"=>33,
                "name"=>"Retención por compras",
            ],            
            [
                "id"=>58,
                "code"=>236570,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "ledgerAccountAccount_id"=>33,
                "name"=>"Otras retenciones",
            ],            
            [
                "id"=>59,
                "code"=>236575,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "ledgerAccountAccount_id"=>33,
                "name"=>"Autorretenciones",
            ],            
            [
                "id"=>60,
                "code"=>236701,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "ledgerAccountAccount_id"=>34,
                "name"=>"Impuesto a las ventas retenido",
            ],            
            [
                "id"=>61,
                "code"=>236705,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "ledgerAccountAccount_id"=>34,
                "name"=>"Retención de impuesto a las ventas Iva",
            ],            
            [
                "id"=>62,
                "code"=>236768,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "ledgerAccountAccount_id"=>34,
                "name"=>"Impuesto a las ventas retenido",
            ],            
            [
                "id"=>63,
                "code"=>236805,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "ledgerAccountAccount_id"=>35,
                "name"=>"Retención industria y comercio Ica",
            ],            
            [
                "id"=>64,
                "code"=>237005,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "ledgerAccountAccount_id"=>36,
                "name"=>"Aportes a entidades promotoras de salud eps",
            ],            
            [
                "id"=>65,
                "code"=>237006,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "ledgerAccountAccount_id"=>36,
                "name"=>"Aporte a administradoras de riesgos profesionales",
            ],            
            [
                "id"=>66,
                "code"=>237010,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "ledgerAccountAccount_id"=>36,
                "name"=>"Aportes al icbf Sena y cajas de compensación",
            ],            
            [
                "id"=>67,
                "code"=>237015,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "ledgerAccountAccount_id"=>36,
                "name"=>"Aportes arl",
            ],            
            [
                "id"=>68,
                "code"=>237025,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "ledgerAccountAccount_id"=>36,
                "name"=>"Embargos judiciales",
            ],            
            [
                "id"=>69,
                "code"=>237030,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "ledgerAccountAccount_id"=>36,
                "name"=>"Libranzas",
            ],                       
            [
                "id"=>70,
                "code"=>237045,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "ledgerAccountAccount_id"=>36,
                "name"=>"Fondos",
            ],            
            [
                "id"=>71,
                "code"=>237050,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "ledgerAccountAccount_id"=>36,
                "name"=>"Ahorro afc",
            ],            
            [
                "id"=>72,
                "code"=>238030,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "ledgerAccountAccount_id"=>37,
                "name"=>"Fondos de cesantías y/o pensiones",
            ],            
            [
                "id"=>73,
                "code"=>238095,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "ledgerAccountAccount_id"=>37,
                "name"=>"Otros",
            ],            
            [
                "id"=>74,
                "code"=>240405,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>13,
                "ledgerAccountAccount_id"=>38,
                "name"=>"Vigencia fiscal corriente",
            ],            
            [
                "id"=>75,
                "code"=>240805,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>13,
                "ledgerAccountAccount_id"=>39,
                "name"=>"Iva generado en ventas",
            ],            
            [
                "id"=>76,
                "code"=>240806,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>13,
                "ledgerAccountAccount_id"=>39,
                "name"=>"Iva generado",
            ],            
            [
                "id"=>77,
                "code"=>240810,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>13,
                "ledgerAccountAccount_id"=>39,
                "name"=>"Iva descontable por compras",
            ],            
            [
                "id"=>78,
                "code"=>240815,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>13,
                "ledgerAccountAccount_id"=>39,
                "name"=>"Descontable por servicios",
            ],            
            [
                "id"=>79,
                "code"=>240820,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>13,
                "ledgerAccountAccount_id"=>39,
                "name"=>"Descontable por devoluciones",
            ],            
            [
                "id"=>80,
                "code"=>240830,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>13,
                "ledgerAccountAccount_id"=>39,
                "name"=>"Descontable régimen simplificado",
            ],            
            [
                "id"=>81,
                "code"=>246401,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>13,
                "ledgerAccountAccount_id"=>40,
                "name"=>"Impuesto por valor en ventas",
            ],            
            [
                "id"=>82,
                "code"=>246402,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>13,
                "ledgerAccountAccount_id"=>40,
                "name"=>"Impuesto por valor en devolucion en ventas",
            ],            
            [
                "id"=>83,
                "code"=>246403,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>13,
                "ledgerAccountAccount_id"=>40,
                "name"=>"Impuesto por valor en compras",
            ],            
            [
                "id"=>84,
                "code"=>246404,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>13,
                "ledgerAccountAccount_id"=>40,
                "name"=>"Impuesto por valor en devolucion en compras",
            ],            
            [
                "id"=>85,
                "code"=>249501,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>13,
                "ledgerAccountAccount_id"=>41,
                "name"=>"Impuesto al consumo nacional",
            ],            
            [
                "id"=>86,
                "code"=>250505,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>14,
                "ledgerAccountAccount_id"=>42,
                "name"=>"Salarios por pagar",
            ],            
            [
                "id"=>87,
                "code"=>251010,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>14,
                "ledgerAccountAccount_id"=>43,
                "name"=>"Pasivo estimado para obligaciones laborales",
            ],            
            [
                "id"=>88,
                "code"=>280505,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>15,
                "ledgerAccountAccount_id"=>44,
                "name"=>"De clientes",
            ],            
            [
                "id"=>89,
                "code"=>281505,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>15,
                "ledgerAccountAccount_id"=>45,
                "name"=>"Valores recibidos para terceros",
            ],            
            [
                "id"=>90,
                "code"=>310505,
                "ledgerAccountClass_id"=>3,
                "ledgerAccountGroup_id"=>16,
                "ledgerAccountAccount_id"=>46,
                "name"=>"Capital suscrito y pagado",
            ],            
            [
                "id"=>91,
                "code"=>310510,
                "ledgerAccountClass_id"=>3,
                "ledgerAccountGroup_id"=>16,
                "ledgerAccountAccount_id"=>46,
                "name"=>"Capital por suscribir (db)",
            ],                        
            [
                "id"=>92,
                "code"=>320505,
                "ledgerAccountClass_id"=>3,
                "ledgerAccountGroup_id"=>17,
                "ledgerAccountAccount_id"=>47,
                "name"=>"Prima en colocación de acciones",
            ],            
            [
                "id"=>93,
                "code"=>320520,
                "ledgerAccountClass_id"=>3,
                "ledgerAccountGroup_id"=>17,
                "ledgerAccountAccount_id"=>47,
                "name"=>"Superávit por el método de participación",
            ],            
            [
                "id"=>94,
                "code"=>330505,
                "ledgerAccountClass_id"=>3,
                "ledgerAccountGroup_id"=>18,
                "ledgerAccountAccount_id"=>48,
                "name"=>"Reservas obligatorias",
            ],            
            [
                "id"=>95,
                "code"=>360505,
                "ledgerAccountClass_id"=>3,
                "ledgerAccountGroup_id"=>19,
                "ledgerAccountAccount_id"=>49,
                "name"=>"Utilidad del ejercicio",
            ],            
            [
                "id"=>96,
                "code"=>360597,
                "ledgerAccountClass_id"=>3,
                "ledgerAccountGroup_id"=>19,
                "ledgerAccountAccount_id"=>49,
                "name"=>"Utilidad del ejercicio Fiscal",
            ],            
            [
                "id"=>97,
                "code"=>361005,
                "ledgerAccountClass_id"=>3,
                "ledgerAccountGroup_id"=>19,
                "ledgerAccountAccount_id"=>50,
                "name"=>"Perdida del ejercicio",
            ],            
            [
                "id"=>98,
                "code"=>361097,
                "ledgerAccountClass_id"=>3,
                "ledgerAccountGroup_id"=>19,
                "ledgerAccountAccount_id"=>50,
                "name"=>"Perdida del ejercicio Fiscal",
            ],            
            [
                "id"=>99,
                "code"=>370505,
                "ledgerAccountClass_id"=>3,
                "ledgerAccountGroup_id"=>20,
                "ledgerAccountAccount_id"=>51,
                "name"=>"Resultados de ejercicios anteriores",
            ],            
            [
                "id"=>100,
                "code"=>371005,
                "ledgerAccountClass_id"=>3,
                "ledgerAccountGroup_id"=>20,
                "ledgerAccountAccount_id"=>52,
                "name"=>"Convergencia",
            ],            
            [
                "id"=>101,
                "code"=>390505,
                "ledgerAccountClass_id"=>3,
                "ledgerAccountGroup_id"=>21,
                "ledgerAccountAccount_id"=>53,
                "name"=>"Resultados fiscales de ventas en ganancia ocasional",
            ],            
            [
                "id"=>102,
                "code"=>412079,
                "ledgerAccountClass_id"=>4,
                "ledgerAccountGroup_id"=>22,
                "ledgerAccountAccount_id"=>54,
                "name"=>"Fabricacion de partes piezas y accesorios para aut",
            ],            
            [
                "id"=>103,
                "code"=>413501,
                "ledgerAccountClass_id"=>4,
                "ledgerAccountGroup_id"=>22,
                "ledgerAccountAccount_id"=>55,
                "name"=>"Comercio al por mayor y al detal",
            ],            
            [
                "id"=>104,
                "code"=>417505,
                "ledgerAccountClass_id"=>4,
                "ledgerAccountGroup_id"=>22,
                "ledgerAccountAccount_id"=>56,
                "name"=>"Devolución",
            ],            
            [
                "id"=>105,
                "code"=>418001,
                "ledgerAccountClass_id"=>4,
                "ledgerAccountGroup_id"=>22,
                "ledgerAccountAccount_id"=>57,
                "name"=>"Servicios",
            ],            
            [
                "id"=>106,
                "code"=>421020,
                "ledgerAccountClass_id"=>4,
                "ledgerAccountGroup_id"=>23,
                "ledgerAccountAccount_id"=>58,
                "name"=>"Diferencia en cambio",
            ],            
            [
                "id"=>107,
                "code"=>421040,
                "ledgerAccountClass_id"=>4,
                "ledgerAccountGroup_id"=>23,
                "ledgerAccountAccount_id"=>58,
                "name"=>"Descuentos comerciales condicionados",
            ],            
            [
                "id"=>108,
                "code"=>421805,
                "ledgerAccountClass_id"=>4,
                "ledgerAccountGroup_id"=>23,
                "ledgerAccountAccount_id"=>59,
                "name"=>"De sociedades anónimas y/o asimiladas",
            ],            
            [
                "id"=>109,
                "code"=>429505,
                "ledgerAccountClass_id"=>4,
                "ledgerAccountGroup_id"=>23,
                "ledgerAccountAccount_id"=>60,
                "name"=>"Aprovechamientos",
            ],            
            [
                "id"=>110,
                "code"=>429581,
                "ledgerAccountClass_id"=>4,
                "ledgerAccountGroup_id"=>23,
                "ledgerAccountAccount_id"=>60,
                "name"=>"Ajuste al peso",
            ],            
            [
                "id"=>111,
                "code"=>429595,
                "ledgerAccountClass_id"=>4,
                "ledgerAccountGroup_id"=>23,
                "ledgerAccountAccount_id"=>60,
                "name"=>"Ingresos diversos POS",
            ],            
            [
                "id"=>112,
                "code"=>430505,
                "ledgerAccountClass_id"=>4,
                "ledgerAccountGroup_id"=>24,
                "ledgerAccountAccount_id"=>61,
                "name"=>"Revaluación",
            ],            
            [
                "id"=>113,
                "code"=>430510,
                "ledgerAccountClass_id"=>4,
                "ledgerAccountGroup_id"=>24,
                "ledgerAccountAccount_id"=>61,
                "name"=>"Salvamento",
            ],            
            [
                "id"=>114,
                "code"=>440505,
                "ledgerAccountClass_id"=>4,
                "ledgerAccountGroup_id"=>25,
                "ledgerAccountAccount_id"=>62,
                "name"=>"Ingresos por ganancia ocasional",
            ],            
            [
                "id"=>115,
                "code"=>441005,
                "ledgerAccountClass_id"=>4,
                "ledgerAccountGroup_id"=>25,
                "ledgerAccountAccount_id"=>63,
                "name"=>"Recuperación de deducciones fiscales",
            ],                        
            [
                "id"=>116,
                "code"=>510503,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>64,
                "name"=>"Salario integral",
            ],            
            [
                "id"=>117,
                "code"=>510506,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>64,
                "name"=>"Sueldos",
            ],            
            [
                "id"=>118,
                "code"=>510512,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>64,
                "name"=>"Apoyo sostenimiento aprendices",
            ],            
            [
                "id"=>119,
                "code"=>510515,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>64,
                "name"=>"Horas extras y recargos",
            ],            
            [
                "id"=>120,
                "code"=>510524,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>64,
                "name"=>"Incapacidades",
            ],            
            [
                "id"=>121,
                "code"=>510527,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>64,
                "name"=>"Auxilio de transporte",
            ],            
            [
                "id"=>122,
                "code"=>510530,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>64,
                "name"=>"Cesantías",
            ],            
            [
                "id"=>123,
                "code"=>510533,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>64,
                "name"=>"Intereses sobre cesantías",
            ],            
            [
                "id"=>124,
                "code"=>510536,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>64,
                "name"=>"Prima de servicios",
            ],            
            [
                "id"=>125,
                "code"=>510539,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>64,
                "name"=>"Vacaciones",
            ],            
            [
                "id"=>126,
                "code"=>510545,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>64,
                "name"=>"Auxilios",
            ],            
            [
                "id"=>127,
                "code"=>510548,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>64,
                "name"=>"Bonificaciones",
            ],            
            [
                "id"=>128,
                "code"=>510551,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>64,
                "name"=>"Dotación y suministro a trabajadores",
            ],            
            [
                "id"=>129,
                "code"=>510560,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>64,
                "name"=>"Indemnizaciones laborales",
            ],            
            [
                "id"=>130,
                "code"=>510563,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>64,
                "name"=>"Capacitación al personal",
            ],            
            [
                "id"=>131,
                "code"=>510566,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>64,
                "name"=>"Gastos deportivos y de recreación",
            ],            
            [
                "id"=>132,
                "code"=>510568,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>64,
                "name"=>"Aportes a administradora de riesgos laborales",
            ],            
            [
                "id"=>133,
                "code"=>510569,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>64,
                "name"=>"Aportes a entidades promotoras de salud eps",
            ],            
            [
                "id"=>134,
                "code"=>510570,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>64,
                "name"=>"Aporte a fondos de pensión y/o cesantías",
            ],            
            [
                "id"=>135,
                "code"=>510572,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>64,
                "name"=>"Aportes cajas de compensación familiar",
            ],            
            [
                "id"=>136,
                "code"=>510575,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>64,
                "name"=>"Aportes icbf",
            ],            
            [
                "id"=>137,
                "code"=>510578,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>64,
                "name"=>"Aportes Sena",
            ],            
            [
                "id"=>138,
                "code"=>510584,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>64,
                "name"=>"Gastos médicos y drogas",
            ],            
            [
                "id"=>139,
                "code"=>510595,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>64,
                "name"=>"Otros",
            ],            
            [
                "id"=>140,
                "code"=>511010,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>65,
                "name"=>"Revisoría fiscal",
            ],            
            [
                "id"=>141,
                "code"=>511015,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>65,
                "name"=>"Auditoria externa",
            ],            
            [
                "id"=>142,
                "code"=>511020,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>65,
                "name"=>"Avalúos",
            ],            
            [
                "id"=>143,
                "code"=>511025,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>65,
                "name"=>"Asesoría jurídica",
            ],            
            [
                "id"=>144,
                "code"=>511035,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>65,
                "name"=>"Asesoría técnica",
            ],            
            [
                "id"=>145,
                "code"=>511505,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>66,
                "name"=>"Industria y comercio",
            ],            
            [
                "id"=>146,
                "code"=>511515,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>66,
                "name"=>"A la propiedad raíz",
            ],            
            [
                "id"=>147,
                "code"=>511540,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>66,
                "name"=>"De vehículos",
            ],            
            [
                "id"=>148,
                "code"=>511570,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>66,
                "name"=>"Prorrateo de Iva",
            ],            
            [
                "id"=>149,
                "code"=>511595,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>66,
                "name"=>"Otros impuestos ",
            ],            
            [
                "id"=>150,
                "code"=>512010,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>67,
                "name"=>"Construcciones y edificaciones",
            ],            
            [
                "id"=>151,
                "code"=>512020,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>67,
                "name"=>"Equipo de oficina",
            ],            
            [
                "id"=>152,
                "code"=>512025,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>67,
                "name"=>"Equipo de computación",
            ],            
            [
                "id"=>153,
                "code"=>512095,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>67,
                "name"=>"Bodegaje",
            ],            
            [
                "id"=>154,
                "code"=>512510,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>68,
                "name"=>"Afiliaciones y sostenimiento",
            ],            
            [
                "id"=>155,
                "code"=>513010,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>69,
                "name"=>"Cumplimiento",
            ],            
            [
                "id"=>156,
                "code"=>513015,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>69,
                "name"=>"Corriente débil",
            ],            
            [
                "id"=>157,
                "code"=>513020,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>69,
                "name"=>"Vida colectiva",
            ],            
            [
                "id"=>158,
                "code"=>513030,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>69,
                "name"=>"Terremoto",
            ],            
            [
                "id"=>159,
                "code"=>513035,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>69,
                "name"=>"Sustracción y hurto",
            ],            
            [
                "id"=>160,
                "code"=>513040,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>69,
                "name"=>"Flota y equipo de transporte",
            ],            
            [
                "id"=>161,
                "code"=>513070,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>69,
                "name"=>"Rotura de maquinaria",
            ],            
            [
                "id"=>162,
                "code"=>513075,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>69,
                "name"=>"Obligatorio accidente de transito",
            ],            
            [
                "id"=>163,
                "code"=>513505,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>70,
                "name"=>"Aseo y vigilancia",
            ],            
            [
                "id"=>164,
                "code"=>513520,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>70,
                "name"=>"Procesamiento electrónico de datos",
            ],            
            [
                "id"=>165,
                "code"=>513525,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>70,
                "name"=>"Acueducto y alcantarillado",
            ],            
            [
                "id"=>166,
                "code"=>513530,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>70,
                "name"=>"Energía eléctrica",
            ],            
            [
                "id"=>167,
                "code"=>513535,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>70,
                "name"=>"Teléfono",
            ],            
            [
                "id"=>168,
                "code"=>513540,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>70,
                "name"=>"Correo portes y telegramas",
            ],            
            [
                "id"=>169,
                "code"=>513550,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>70,
                "name"=>"Transporte fletes y acarreos",
            ],            
            [
                "id"=>170,
                "code"=>513555,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>70,
                "name"=>"Gas",
            ],            
            [
                "id"=>171,
                "code"=>513595,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>70,
                "name"=>"Otros",
            ],            
            [
                "id"=>172,
                "code"=>514005,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>71,
                "name"=>"Notariales",
            ],            
            [
                "id"=>173,
                "code"=>514010,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>71,
                "name"=>"Registro mercantil",
            ],            
            [
                "id"=>174,
                "code"=>514015,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>71,
                "name"=>"Tramites y licencias",
            ],            
            [
                "id"=>175,
                "code"=>514095,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>71,
                "name"=>"Otros",
            ],            
            [
                "id"=>176,
                "code"=>514510,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>72,
                "name"=>"Construcciones y edificaciones",
            ],            
            [
                "id"=>177,
                "code"=>514520,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>72,
                "name"=>"Equipo de oficina",
            ],            
            [
                "id"=>178,
                "code"=>514525,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>72,
                "name"=>"Equipo de computación y comunicación",
            ],            
            [
                "id"=>179,
                "code"=>514540,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>72,
                "name"=>"Flota y equipo de transporte",
            ],            
            [
                "id"=>180,
                "code"=>515005,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>73,
                "name"=>"Instalaciones eléctricas",
            ],            
            [
                "id"=>181,
                "code"=>515010,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>73,
                "name"=>"Arreglos ornamentales",
            ],            
            [
                "id"=>182,
                "code"=>515015,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>73,
                "name"=>"Reparaciones locativas",
            ],            
            [
                "id"=>183,
                "code"=>515020,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>73,
                "name"=>"Adecuación de puestos de trabajo",
            ],            
            [
                "id"=>184,
                "code"=>515505,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>74,
                "name"=>"Alojamiento y manutención",
            ],            
            [
                "id"=>185,
                "code"=>515515,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>74,
                "name"=>"Pasajes aéreos",
            ],            
            [
                "id"=>186,
                "code"=>515520,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>74,
                "name"=>"Pasajes terrestres",
            ],            
            [
                "id"=>187,
                "code"=>515595,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>74,
                "name"=>"Otros gastos de viaje",
            ],            
            [
                "id"=>188,
                "code"=>516005,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>75,
                "name"=>"Construcciones y edificaciones",
            ],            
            [
                "id"=>189,
                "code"=>516015,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>75,
                "name"=>"Equipo de oficina",
            ],            
            [
                "id"=>190,
                "code"=>516020,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>75,
                "name"=>"Equipo de computación y comunicación",
            ],            
            [
                "id"=>191,
                "code"=>516035,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>75,
                "name"=>"Flota y equipo de transporte",
            ],            
            [
                "id"=>192,
                "code"=>516510,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>76,
                "name"=>"Intangibles",
            ],            
            [
                "id"=>193,
                "code"=>516515,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>76,
                "name"=>"Cargos diferidos",
            ],            
            [
                "id"=>194,
                "code"=>519510,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>77,
                "name"=>"Libros suscripciones periódicos y revistas",
            ],            
            [
                "id"=>195,
                "code"=>519515,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>77,
                "name"=>"Elementos ferreteria",
            ],            
            [
                "id"=>196,
                "code"=>519520,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>77,
                "name"=>"Gastos de representación y relaciones publicas",
            ],            
            [
                "id"=>197,
                "code"=>519525,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>77,
                "name"=>"Elementos de aseo y cafetería",
            ],            
            [
                "id"=>198,
                "code"=>519530,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>77,
                "name"=>"Útiles papelería y fotocopias",
            ],            
            [
                "id"=>199,
                "code"=>519535,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>77,
                "name"=>"Combustibles y lubricantes",
            ],            
            [
                "id"=>200,
                "code"=>519545,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>77,
                "name"=>"Taxis y buses",
            ],            
            [
                "id"=>201,
                "code"=>519560,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>77,
                "name"=>"Casino y restaurante",
            ],            
            [
                "id"=>202,
                "code"=>519565,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>77,
                "name"=>"Parqueaderos",
            ],            
            [
                "id"=>203,
                "code"=>519590,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>77,
                "name"=>"Impuestos asumidos",
            ],            
            [
                "id"=>204,
                "code"=>519595,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>77,
                "name"=>"Otros",
            ],            
            [
                "id"=>205,
                "code"=>519905,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>78,
                "name"=>"Inversiones",
            ],            
            [
                "id"=>206,
                "code"=>519999,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "ledgerAccountAccount_id"=>78,
                "name"=>"Otros gastos",
            ],            
            [
                "id"=>207,
                "code"=>520503,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>79,
                "name"=>"Salario integral",
            ],            
            [
                "id"=>208,
                "code"=>520506,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>79,
                "name"=>"Sueldos",
            ],            
            [
                "id"=>209,
                "code"=>520512,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>79,
                "name"=>"Apoyo sostenimiento aprendices",
            ],            
            [
                "id"=>210,
                "code"=>520515,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>79,
                "name"=>"Horas extras y recargos",
            ],            
            [
                "id"=>211,
                "code"=>520524,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>79,
                "name"=>"Incapacidades",
            ],            
            [
                "id"=>212,
                "code"=>520527,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>79,
                "name"=>"Auxilio de transporte",
            ],            
            [
                "id"=>213,
                "code"=>520530,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>79,
                "name"=>"Cesantías",
            ],            
            [
                "id"=>214,
                "code"=>520533,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>79,
                "name"=>"Intereses sobre cesantías",
            ],            
            [
                "id"=>215,
                "code"=>520536,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>79,
                "name"=>"Prima de servicios",
            ],            
            [
                "id"=>216,
                "code"=>520539,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>79,
                "name"=>"Vacaciones",
            ],            
            [
                "id"=>217,
                "code"=>520545,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>79,
                "name"=>"Auxilios",
            ],            
            [
                "id"=>218,
                "code"=>520548,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>79,
                "name"=>"Bonificaciones",
            ],            
            [
                "id"=>219,
                "code"=>520551,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>79,
                "name"=>"Dotación y suministro a trabajadores",
            ],            
            [
                "id"=>220,
                "code"=>520560,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>79,
                "name"=>"Indemnizaciones laborales",
            ],            
            [
                "id"=>221,
                "code"=>520563,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>79,
                "name"=>"Capacitación al personal",
            ],            
            [
                "id"=>222,
                "code"=>520566,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>79,
                "name"=>"Gastos deportivos y de recreación",
            ],            
            [
                "id"=>223,
                "code"=>520568,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>79,
                "name"=>"Aportes a administradora de riesgos laborales",
            ],            
            [
                "id"=>224,
                "code"=>520569,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>79,
                "name"=>"Aportes a entidades promotoras de salud eps",
            ],            
            [
                "id"=>225,
                "code"=>520570,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>79,
                "name"=>"Aporte a fondos de pensión y/o cesantías",
            ],            
            [
                "id"=>226,
                "code"=>520572,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>79,
                "name"=>"Aportes cajas de compensación familiar",
            ],            
            [
                "id"=>227,
                "code"=>520575,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>79,
                "name"=>"Aportes icbf",
            ],            
            [
                "id"=>228,
                "code"=>520578,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>79,
                "name"=>"Aportes Sena",
            ],            
            [
                "id"=>229,
                "code"=>520584,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>79,
                "name"=>"Gastos médicos y drogas",
            ],            
            [
                "id"=>230,
                "code"=>520595,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>79,
                "name"=>"Otros",
            ],
            [
                "id"=>231,
                "code"=>523510,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>80,
                "name"=>"Temporales",  
            ],            
            [
                "id"=>232,
                "code"=>523535,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>80,
                "name"=>"Teléfono",  
            ],            
            [
                "id"=>233,
                "code"=>523540,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>80,
                "name"=>"Correo portes y telegramas",  
            ],            
            [
                "id"=>234,
                "code"=>523560,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>80,
                "name"=>"Publicidad propaganda y promoción",  
            ],            
            [
                "id"=>235,
                "code"=>525515,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>81,
                "name"=>"Pasajes aéreos comercial",  
            ],            
            [
                "id"=>236,
                "code"=>529505,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>82,
                "name"=>"Comisiones",  
            ],            
            [
                "id"=>237,
                "code"=>529545,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>82,
                "name"=>"Taxis y buses",  
            ],            
            [
                "id"=>238,
                "code"=>529595,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "ledgerAccountAccount_id"=>82,
                "name"=>"Otros diversos",  
            ],            
            [
                "id"=>239,
                "code"=>530505,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>28,
                "ledgerAccountAccount_id"=>83,
                "name"=>"Gastos bancarios",  
            ],            
            [
                "id"=>240,
                "code"=>530515,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>28,
                "ledgerAccountAccount_id"=>83,
                "name"=>"Comisiones",  
            ],            
            [
                "id"=>241,
                "code"=>530520,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>28,
                "ledgerAccountAccount_id"=>83,
                "name"=>"Intereses",  
            ],            
            [
                "id"=>242,
                "code"=>530525,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>28,
                "ledgerAccountAccount_id"=>83,
                "name"=>"Diferencia en cambio",  
            ],            
            [
                "id"=>243,
                "code"=>530535,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>28,
                "ledgerAccountAccount_id"=>83,
                "name"=>"Descuentos comerciales condicionados",  
            ],            
            [
                "id"=>244,
                "code"=>531030,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>28,
                "ledgerAccountAccount_id"=>84,
                "name"=>"Retiro de propiedades planta y equipo",  
            ],            
            [
                "id"=>245,
                "code"=>531515,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>28,
                "ledgerAccountAccount_id"=>85,
                "name"=>"Costos y gastos de ejercicios anteriores",  
            ],            
            [
                "id"=>246,
                "code"=>531520,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>28,
                "ledgerAccountAccount_id"=>85,
                "name"=>"Impuestos asumidos",  
            ],            
            [
                "id"=>247,
                "code"=>531525,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>28,
                "ledgerAccountAccount_id"=>85,
                "name"=>"Costos y gastos no deducibles",  
            ],            
            [
                "id"=>248,
                "code"=>539520,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>28,
                "ledgerAccountAccount_id"=>86,
                "name"=>"Multas sanciones y litigios",  
            ],            
            [
                "id"=>249,
                "code"=>539525,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>28,
                "ledgerAccountAccount_id"=>86,
                "name"=>"Donaciones",  
            ],            
            [
                "id"=>250,
                "code"=>539581,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>28,
                "ledgerAccountAccount_id"=>86,
                "name"=>"Ajuste al peso",  
            ],            
            [
                "id"=>251,
                "code"=>539595,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>28,
                "ledgerAccountAccount_id"=>86,
                "name"=>"Otros",  
            ],            
            [
                "id"=>252,
                "code"=>540505,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>29,
                "ledgerAccountAccount_id"=>87,
                "name"=>"Impuesto de renta y complementarios",  
            ],            
            [
                "id"=>253,
                "code"=>540510,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>29,
                "ledgerAccountAccount_id"=>87,
                "name"=>"Cree",  
            ],            
            [
                "id"=>254,
                "code"=>540515,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>29,
                "ledgerAccountAccount_id"=>87,
                "name"=>"Impuesto a la riqueza",  
            ],            
            [
                "id"=>255,
                "code"=>612079,
                "ledgerAccountClass_id"=>6,
                "ledgerAccountGroup_id"=>30,
                "ledgerAccountAccount_id"=>88,
                "name"=>"Fabricacion de partes piezas y accesorios para aut",  
            ],            
            [
                "id"=>256,
                "code"=>613505,
                "ledgerAccountClass_id"=>6,
                "ledgerAccountGroup_id"=>30,
                "ledgerAccountAccount_id"=>89,
                "name"=>"Comercio al por mayor y al por menor",  
            ],            
            [
                "id"=>257,
                "code"=>618001,
                "ledgerAccountClass_id"=>6,
                "ledgerAccountGroup_id"=>30,
                "ledgerAccountAccount_id"=>90,
                "name"=>"Servicios",  
            ],            
            [
                "id"=>258,
                "code"=>710505,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>31,
                "ledgerAccountAccount_id"=>91,
                "name"=>"Costos de producción o de operación",  
            ],            
            [
                "id"=>259,
                "code"=>720503,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>32,
                "ledgerAccountAccount_id"=>92,
                "name"=>"Salario integral",  
            ],            
            [
                "id"=>260,
                "code"=>720506,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>32,
                "ledgerAccountAccount_id"=>92,
                "name"=>"Sueldos",  
            ],            
            [
                "id"=>261,
                "code"=>720512,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>32,
                "ledgerAccountAccount_id"=>92,
                "name"=>"Apoyo sostenimiento aprendices",  
            ],            
            [
                "id"=>262,
                "code"=>720515,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>32,
                "ledgerAccountAccount_id"=>92,
                "name"=>"Horas extras y recargos",  
            ],            
            [
                "id"=>263,
                "code"=>720524,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>32,
                "ledgerAccountAccount_id"=>92,
                "name"=>"Incapacidades",  
            ],            
            [
                "id"=>264,
                "code"=>720527,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>32,
                "ledgerAccountAccount_id"=>92,
                "name"=>"Auxilio de transporte",  
            ],            
            [
                "id"=>265,
                "code"=>720530,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>32,
                "ledgerAccountAccount_id"=>92,
                "name"=>"Cesantías",  
            ],            
            [
                "id"=>266,
                "code"=>720533,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>32,
                "ledgerAccountAccount_id"=>92,
                "name"=>"Intereses sobre cesantías",  
            ],            
            [
                "id"=>267,
                "code"=>720536,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>32,
                "ledgerAccountAccount_id"=>92,
                "name"=>"Prima de servicios",  
            ],            
            [
                "id"=>268,
                "code"=>720539,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>32,
                "ledgerAccountAccount_id"=>92,
                "name"=>"Vacaciones",  
            ],            
            [
                "id"=>269,
                "code"=>720545,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>32,
                "ledgerAccountAccount_id"=>92,
                "name"=>"Auxilios",  
            ],            
            [
                "id"=>270,
                "code"=>720548,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>32,
                "ledgerAccountAccount_id"=>92,
                "name"=>"Bonificaciones",  
            ],            
            [
                "id"=>271,
                "code"=>720551,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>32,
                "ledgerAccountAccount_id"=>92,
                "name"=>"Dotación y suministro a trabajadores",  
            ],            
            [
                "id"=>272,
                "code"=>720560,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>32,
                "ledgerAccountAccount_id"=>92,
                "name"=>"Indemnizaciones laborales",  
            ],            
            [
                "id"=>273,
                "code"=>720563,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>32,
                "ledgerAccountAccount_id"=>92,
                "name"=>"Capacitación al personal",  
            ],            
            [
                "id"=>274,
                "code"=>720566,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>32,
                "ledgerAccountAccount_id"=>92,
                "name"=>"Gastos deportivos y de recreación",  
            ],            
            [
                "id"=>275,
                "code"=>720568,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>32,
                "ledgerAccountAccount_id"=>92,
                "name"=>"Aportes a administradora de riesgos laborales",  
            ],            
            [
                "id"=>276,
                "code"=>720569,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>32,
                "ledgerAccountAccount_id"=>92,
                "name"=>"Aportes a entidades promotoras de salud eps",  
            ],            
            [
                "id"=>277,
                "code"=>720570,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>32,
                "ledgerAccountAccount_id"=>92,
                "name"=>"Aporte a fondos de pensión y/o cesantías",  
            ],            
            [
                "id"=>278,
                "code"=>720572,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>32,
                "ledgerAccountAccount_id"=>92,
                "name"=>"Aportes cajas de compensación familiar",  
            ],            
            [
                "id"=>279,
                "code"=>720575,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>32,
                "ledgerAccountAccount_id"=>92,
                "name"=>"Aportes icbf",  
            ],            
            [
                "id"=>280,
                "code"=>720578,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>32,
                "ledgerAccountAccount_id"=>92,
                "name"=>"Aportes Sena",  
            ],            
            [
                "id"=>281,
                "code"=>720584,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>32,
                "ledgerAccountAccount_id"=>92,
                "name"=>"Gastos médicos y drogas",  
            ],            
            [
                "id"=>282,
                "code"=>720595,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>32,
                "ledgerAccountAccount_id"=>92,
                "name"=>"Otros",  
            ],            
            [
                "id"=>283,
                "code"=>730505,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>33,
                "ledgerAccountAccount_id"=>93,
                "name"=>"Costos indirectos",  
            ],                      
            [
                "id"=>284,
                "code"=>740505,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>34,
                "ledgerAccountAccount_id"=>94,
                "name"=>"Contratos de servicios",  
            ],            
            [
                "id"=>285,
                "code"=>810105,
                "ledgerAccountClass_id"=>8,
                "ledgerAccountGroup_id"=>35,
                "ledgerAccountAccount_id"=>95,
                "name"=>"EFECTIVO",  
            ],            
            [
                "id"=>286,
                "code"=>999999,
                "ledgerAccountClass_id"=>9,
                "ledgerAccountGroup_id"=>36,
                "ledgerAccountAccount_id"=>96,
                "name"=>"Saldos iniciales por conciliar",  
            ],            
        ];
        foreach ($arrayData as $key => $value) {
            $data = new LedgerAccountSubAccount();
            $data->id = $value["id"];
            $data->code = $value["code"];
            $data->name = $value["name"];
            $data->ledgerAccountClass_id = $value["ledgerAccountClass_id"];
            $data->ledgerAccountGroup_id = $value["ledgerAccountGroup_id"]; 
            $data->ledgerAccountAccount_id = $value["ledgerAccountAccount_id"]; 
            $data->save();
        }
    }
}
