<?php

namespace Database\Seeders;

use App\Models\LedgerAccountAccount;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class LedgerAccountAccountSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $arrayData=[
            [
                "id"=>1,
                "code"=>1105,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>1,
                "name"=>"Caja",
            ],
            [
                "id"=>2,
                "code"=>1110,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>1,
                "name"=>"Bancos",
            ],
            [
                "id"=>3,
                "code"=>1120,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>1,
                "name"=>"Cuentas de ahorro",
            ],
            [
                "id"=>4,
                "code"=>1145,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>1,
                "name"=>"Inversiones en efectivo",
            ],
            [
                "id"=>5,
                "code"=>1205,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>2,
                "name"=>"Acciones",
            ],
            [
                "id"=>6,
                "code"=>1295,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>2,
                "name"=>"Acciones o derechos en clubes deportivos",
            ],
            [
                "id"=>7,
                "code"=>1305,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>3,
                "name"=>"Clientes nacionales",
            ],
            [
                "id"=>8,
                "code"=>1325,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>3,
                "name"=>"Cuentas por cobrar a socios y accionistas",
            ],
            [
                "id"=>9,
                "code"=>1330,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>3,
                "name"=>"Anticipos y avances",
            ],
            [
                "id"=>10,
                "code"=>1355,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>3,
                "name"=>"Anticipos de impuestos y contribuciones o",
            ],
            [
                "id"=>11,
                "code"=>1365,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>3,
                "name"=>"Cuentas por cobrar a trabajadores",
            ],
            [
                "id"=>12,
                "code"=>1380,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>3,
                "name"=>"Deudores varios",
            ],
            [
                "id"=>13,
                "code"=>1399,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>3,
                "name"=>"Provisiones",
            ],
            [
                "id"=>14,
                "code"=>1420,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>4,
                "name"=>"Industrias manufactureras",
            ],
            [
                "id"=>15,
                "code"=>1435,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>4,
                "name"=>"Mercancías no fabricadas por la empresa",
            ],
            [
                "id"=>16,
                "code"=>1498,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>4,
                "name"=>"Otros",
            ],
            [
                "id"=>17,
                "code"=>1504,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>5,
                "name"=>"Terrenos",
            ],
            [
                "id"=>18,
                "code"=>1516,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>5,
                "name"=>"Construcciones y edificaciones",
            ],
            [
                "id"=>19,
                "code"=>1524,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>5,
                "name"=>"Equipo de oficina",
            ],
            [
                "id"=>20,
                "code"=>1528,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>5,
                "name"=>"Equipo de computación y comunicación",
            ],
            [
                "id"=>21,
                "code"=>1540,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>5,
                "name"=>"Flota y equipo de transporte",
            ],
            [
                "id"=>22,
                "code"=>1592,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>5,
                "name"=>"Depreciación acumulada",
            ],
            [
                "id"=>23,
                "code"=>1635,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>6,
                "name"=>"Licencias",
            ],
            [
                "id"=>24,
                "code"=>1720,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>7,
                "name"=>"Entidades controladas en forma conjunta",
            ],
            [
                "id"=>25,
                "code"=>1805,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>8,
                "name"=>"Impuesto corriente",
            ],
            [
                "id"=>26,
                "code"=>1945,
                "ledgerAccountClass_id"=>1,
                "ledgerAccountGroup_id"=>9,
                "name"=>"De inversiones",
            ],
            [
                "id"=>27,
                "code"=>2105,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>10,
                "name"=>"Bancos nacionales",
            ],
            [
                "id"=>28,
                "code"=>2110,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>10,
                "name"=>"Depósitos recibidos",
            ],
            [
                "id"=>29,
                "code"=>2205,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>11,
                "name"=>"Proveedores nacionales",
            ],
            [
                "id"=>30,
                "code"=>2210,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>11,
                "name"=>"Proveedores del exterior",
            ],
            [
                "id"=>31,
                "code"=>2305,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "name"=>"Cuentas corrientes",
            ],
            [
                "id"=>32,
                "code"=>2335,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "name"=>"Costos y gastos por pagar",
            ],
            [
                "id"=>33,
                "code"=>2365,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "name"=>"Retenciones en la fuente",
            ],
            [
                "id"=>34,
                "code"=>2367,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "name"=>"Impuesto a las ventas retenido",
            ],
            [
                "id"=>35,
                "code"=>2368,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "name"=>"Impuesto de industria y comercio retenido",
            ],
            [
                "id"=>36,
                "code"=>2370,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "name"=>"Aportes a empresas promotoras de salud eps",
            ],
            [
                "id"=>37,
                "code"=>2380,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>12,
                "name"=>"Acreedores varios",
            ],
            [
                "id"=>38,
                "code"=>2404,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>13,
                "name"=>"De renta y complementarios corriente",
            ],
            [
                "id"=>39,
                "code"=>2408,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>13,
                "name"=>"Impuesto sobre las ventas por pagar",
            ],
            [
                "id"=>40,
                "code"=>2464,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>13,
                "name"=>"De licores, cervezas y cigarrillos",
            ],
            [
                "id"=>41,
                "code"=>2495,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>13,
                "name"=>"Otros",
            ],
            [
                "id"=>42,
                "code"=>2505,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>14,
                "name"=>"Salarios por pagar",
            ],
            [
                "id"=>43,
                "code"=>2510,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>14,
                "name"=>"Pasivo estimado para obligaciones laborales",
            ],
            [
                "id"=>44,
                "code"=>2805,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>15,
                "name"=>"Anticipos y avances recibidos",
            ],
            [
                "id"=>45,
                "code"=>2815,
                "ledgerAccountClass_id"=>2,
                "ledgerAccountGroup_id"=>15,
                "name"=>"Ingresos recibidos para terceros",
            ],
            [
                "id"=>46,
                "code"=>3105,
                "ledgerAccountClass_id"=>3,
                "ledgerAccountGroup_id"=>16,
                "name"=>"Capital suscrito y pagado",
            ],
            [
                "id"=>47,
                "code"=>3205,
                "ledgerAccountClass_id"=>3,
                "ledgerAccountGroup_id"=>17,
                "name"=>"Prima en colocación de acciones cuotas o partes d",
            ],
            [
                "id"=>48,
                "code"=>3305,
                "ledgerAccountClass_id"=>3,
                "ledgerAccountGroup_id"=>18,
                "name"=>"Reservas obligatorias",
            ],
            [
                "id"=>49,
                "code"=>3605,
                "ledgerAccountClass_id"=>3,
                "ledgerAccountGroup_id"=>19,
                "name"=>"Utilidad del ejercicio",
            ],
            [
                "id"=>50,
                "code"=>3610,
                "ledgerAccountClass_id"=>3,
                "ledgerAccountGroup_id"=>19,
                "name"=>"Perdida del ejercicio",
            ],
            [
                "id"=>51,
                "code"=>3705,
                "ledgerAccountClass_id"=>3,
                "ledgerAccountGroup_id"=>20,
                "name"=>"Resultados de ejercicios anteriores",
            ],
            [
                "id"=>52,
                "code"=>3710,
                "ledgerAccountClass_id"=>3,
                "ledgerAccountGroup_id"=>20,
                "name"=>"Convergencia",
            ],
            [
                "id"=>53,
                "code"=>3905,
                "ledgerAccountClass_id"=>3,
                "ledgerAccountGroup_id"=>21,
                "name"=>"Resultados fiscales de ventas en ganancia ocasional",
            ],
            [
                "id"=>54,
                "code"=>4120,
                "ledgerAccountClass_id"=>4,
                "ledgerAccountGroup_id"=>22,
                "name"=>"Industrias manufactureras",
            ],
            [
                "id"=>55,
                "code"=>4135,
                "ledgerAccountClass_id"=>4,
                "ledgerAccountGroup_id"=>22,
                "name"=>"Comercio al por mayor y al detal",
            ],
            [
                "id"=>56,
                "code"=>4175,
                "ledgerAccountClass_id"=>4,
                "ledgerAccountGroup_id"=>22,
                "name"=>"Devolución en ventas",
            ],
            [
                "id"=>57,
                "code"=>4180,
                "ledgerAccountClass_id"=>4,
                "ledgerAccountGroup_id"=>22,
                "name"=>"Servicios",
            ],
            [
                "id"=>58,
                "code"=>4210,
                "ledgerAccountClass_id"=>4,
                "ledgerAccountGroup_id"=>23,
                "name"=>"Financieros",
            ],
            [
                "id"=>59,
                "code"=>4218,
                "ledgerAccountClass_id"=>4,
                "ledgerAccountGroup_id"=>23,
                "name"=>"Ingresos método de participación",
            ],
            [
                "id"=>60,
                "code"=>4295,
                "ledgerAccountClass_id"=>4,
                "ledgerAccountGroup_id"=>23,
                "name"=>"Diversos",
            ],
            [
                "id"=>61,
                "code"=>4305,
                "ledgerAccountClass_id"=>4,
                "ledgerAccountGroup_id"=>24,
                "name"=>"Propiedad planta y equipo",
            ],
            [
                "id"=>62,
                "code"=>4405,
                "ledgerAccountClass_id"=>4,
                "ledgerAccountGroup_id"=>25,
                "name"=>"Ingresos por ganancia ocasional",
            ],
            [
                "id"=>63,
                "code"=>4410,
                "ledgerAccountClass_id"=>4,
                "ledgerAccountGroup_id"=>25,
                "name"=>"Ingresos renta ordinaria",
            ],
            [
                "id"=>64,
                "code"=>5105,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "name"=>"Gastos de personal",
            ],
            [
                "id"=>65,
                "code"=>5110,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "name"=>"Honorarios",
            ],
            [
                "id"=>66,
                "code"=>5115,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "name"=>"Impuestos",
            ],
            [
                "id"=>67,
                "code"=>5120,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "name"=>"Arrendamientos",
            ],
            [
                "id"=>68,
                "code"=>5125,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "name"=>"Contribuciones y afiliaciones",
            ],
            [
                "id"=>69,
                "code"=>5130,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "name"=>"Seguros",
            ],
            [
                "id"=>70,
                "code"=>5135,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "name"=>"Servicios",
            ],
            [
                "id"=>71,
                "code"=>5140,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "name"=>"Gastos legales",
            ],
            [
                "id"=>72,
                "code"=>5145,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "name"=>"Mantenimiento y reparaciones",
            ],
            [
                "id"=>73,
                "code"=>5150,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "name"=>"Adecuación e instalación",
            ],
            [
                "id"=>74,
                "code"=>5155,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "name"=>"Gastos de viaje",
            ],
            [
                "id"=>75,
                "code"=>5160,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "name"=>"Depreciaciones",
            ],
            [
                "id"=>76,
                "code"=>5165,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "name"=>"Amortizaciones",
            ],
            [
                "id"=>77,
                "code"=>5195,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "name"=>"Diversos",
            ],
            [
                "id"=>78,
                "code"=>5199,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>26,
                "name"=>"Otros gastos",
            ],
            [
                "id"=>79,
                "code"=>5205,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "name"=>"Gastos de personal",
            ],
            [
                "id"=>80,
                "code"=>5235,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "name"=>"Servicios",
            ],
            [
                "id"=>81,
                "code"=>5255,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "name"=>"Gastos de viaje",
            ],
            [
                "id"=>82,
                "code"=>5295,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>27,
                "name"=>"Diversos",
            ],
            [
                "id"=>83,
                "code"=>5305,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>28,
                "name"=>"Financieros",
            ],
            [
                "id"=>84,
                "code"=>5310,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>28,
                "name"=>"Perdida en venta y retiro de bienes",
            ],
            [
                "id"=>85,
                "code"=>5315,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>28,
                "name"=>"Gastos extraordinarios",
            ],
            [
                "id"=>86,
                "code"=>5395,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>28,
                "name"=>"Gastos diversos",
            ],
            [
                "id"=>87,
                "code"=>5405,
                "ledgerAccountClass_id"=>5,
                "ledgerAccountGroup_id"=>29,
                "name"=>"Impuesto de renta y complementarios",
            ],
            [
                "id"=>88,
                "code"=>6120,
                "ledgerAccountClass_id"=>6,
                "ledgerAccountGroup_id"=>30,
                "name"=>"Industrias manufactureras",
            ],
            [
                "id"=>89,
                "code"=>6135,
                "ledgerAccountClass_id"=>6,
                "ledgerAccountGroup_id"=>30,
                "name"=>"Comercio al por mayor y al por menor",
            ],
            [
                "id"=>90,
                "code"=>6180,
                "ledgerAccountClass_id"=>6,
                "ledgerAccountGroup_id"=>30,
                "name"=>"Servicios",
            ],
            [
                "id"=>91,
                "code"=>7105,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>31,
                "name"=>"Costos de producción o de operación",
            ],
            [
                "id"=>92,
                "code"=>7205,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>32,
                "name"=>"Mano de obra directa",
            ], 
            [
                "id"=>93,
                "code"=>7305,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>33,
                "name"=>"Costos indirectos",
            ],
            [
                "id"=>94,
                "code"=>7405,
                "ledgerAccountClass_id"=>7,
                "ledgerAccountGroup_id"=>34,
                "name"=>"Contratos de servicios",
            ],
            [
                "id"=>95,
                "code"=>8101,
                "ledgerAccountClass_id"=>8,
                "ledgerAccountGroup_id"=>35,
                "name"=>"Caja efectivo",
            ],
            [
                "id"=>96,
                "code"=>9999,
                "ledgerAccountClass_id"=>9,
                "ledgerAccountGroup_id"=>36,
                "name"=>"Saldos iniciales por conciliar",
            ],
        ];

        foreach ($arrayData as $key => $value) {
            $data = new LedgerAccountAccount();
            $data->id =  $value["id"];
            $data->code =  $value["code"];
            $data->ledgerAccountClass_id =  $value["ledgerAccountClass_id"];
            $data->ledgerAccountGroup_id =  $value["ledgerAccountGroup_id"];
            $data->name =  $value["name"];
            $data->save();
        }
    }
}
